local define_soul_wash = {
	["1"] = {
		["magic_atk_min"] = "0",
		["magic_atk_max"] = "2",
		["magic_def_min"] = "0",
		["magic_def_max"] = "2",
		["physical_atk_min"] = "0",
		["physical_atk_max"] = "2",
		["physical_def_min"] = "0",
		["physical_def_max"] = "2",
		["mhp_min"] = "0",
		["mhp_max"] = "2",
		["gold"] = "2",
		["coin"] = "1000",
		["props"] = "5",
		["pot"] = "5",

	},
	["2"] = {
		["magic_atk_min"] = "2",
		["magic_atk_max"] = "5",
		["magic_def_min"] = "2",
		["magic_def_max"] = "5",
		["physical_atk_min"] = "2",
		["physical_atk_max"] = "5",
		["physical_def_min"] = "2",
		["physical_def_max"] = "5",
		["mhp_min"] = "2",
		["mhp_max"] = "5",
		["gold"] = "10",
		["coin"] = "2000",
		["props"] = "5",
		["pot"] = "5",

	},
	["3"] = {
		["magic_atk_min"] = "-2",
		["magic_atk_max"] = "8",
		["magic_def_min"] = "-2",
		["magic_def_max"] = "8",
		["physical_atk_min"] = "-2",
		["physical_atk_max"] = "8",
		["physical_def_min"] = "-2",
		["physical_def_max"] = "8",
		["mhp_min"] = "-2",
		["mhp_max"] = "8",
		["gold"] = "50",
		["coin"] = "5000",
		["props"] = "5",
		["pot"] = "5",

	},
	["4"] = {
		["magic_atk_min"] = "-5",
		["magic_atk_max"] = "15",
		["magic_def_min"] = "-5",
		["magic_def_max"] = "15",
		["physical_atk_min"] = "-5",
		["physical_atk_max"] = "15",
		["physical_def_min"] = "-5",
		["physical_def_max"] = "15",
		["mhp_min"] = "-5",
		["mhp_max"] = "15",
		["gold"] = "300",
		["coin"] = "100000",
		["props"] = "5",
		["pot"] = "5",

	},
	["5"] = {
		["magic_atk_min"] = "-8",
		["magic_atk_max"] = "25",
		["magic_def_min"] = "-8",
		["magic_def_max"] = "25",
		["physical_atk_min"] = "-8",
		["physical_atk_max"] = "25",
		["physical_def_min"] = "-8",
		["physical_def_max"] = "25",
		["mhp_min"] = "-8",
		["mhp_max"] = "25",
		["gold"] = "900",
		["coin"] = "300000",
		["props"] = "5",
		["pot"] = "5",

	},
	["6"] = {
		["magic_atk_min"] = "-20",
		["magic_atk_max"] = "35",
		["magic_def_min"] = "-20",
		["magic_def_max"] = "35",
		["physical_atk_min"] = "-20",
		["physical_atk_max"] = "35",
		["physical_def_min"] = "-20",
		["physical_def_max"] = "35",
		["mhp_min"] = "-20",
		["mhp_max"] = "35",
		["gold"] = "2100",
		["coin"] = "700000",
		["props"] = "5",
		["pot"] = "5",

	},
	["7"] = {
		["magic_atk_min"] = "-30",
		["magic_atk_max"] = "60",
		["magic_def_min"] = "-30",
		["magic_def_max"] = "60",
		["physical_atk_min"] = "-30",
		["physical_atk_max"] = "60",
		["physical_def_min"] = "-30",
		["physical_def_max"] = "60",
		["mhp_min"] = "-30",
		["mhp_max"] = "60",
		["gold"] = "6000",
		["coin"] = "2000000",
		["props"] = "5",
		["pot"] = "5",

	},

}
return define_soul_wash
