local define_streng_factor = {
	["1"] = {
		["quality"] = 1,
		["streng_expend_factor"] = 3,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 5.5,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1,
		["agl_add_factor"] = 3,
		["dex_add_factor"] = 2,
		["type"] = 1,

	},
	["2"] = {
		["quality"] = 2,
		["streng_expend_factor"] = 4,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 6.5,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1.5,
		["agl_add_factor"] = 3.5,
		["dex_add_factor"] = 2,
		["type"] = 1,

	},
	["3"] = {
		["quality"] = 3,
		["streng_expend_factor"] = 6,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 8,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2.5,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 4,
		["dex_add_factor"] = 3,
		["type"] = 1,

	},
	["4"] = {
		["quality"] = 4,
		["streng_expend_factor"] = 9.6666666666667,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 10.5,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 4.5,
		["dex_add_factor"] = 3.5,
		["type"] = 1,

	},
	["5"] = {
		["quality"] = 5,
		["streng_expend_factor"] = 15.666666666667,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 14.5,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 4,
		["block_add_factor"] = 3,
		["agl_add_factor"] = 6,
		["dex_add_factor"] = 4.5,
		["type"] = 1,

	},
	["6"] = {
		["quality"] = 1,
		["streng_expend_factor"] = 0.33333333333333,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 4,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1,
		["agl_add_factor"] = 3,
		["dex_add_factor"] = 2,
		["type"] = 2,

	},
	["7"] = {
		["quality"] = 2,
		["streng_expend_factor"] = 0.66666666666667,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 4.5,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1.5,
		["agl_add_factor"] = 3.5,
		["dex_add_factor"] = 2,
		["type"] = 2,

	},
	["8"] = {
		["quality"] = 3,
		["streng_expend_factor"] = 1,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 6,
		["cri_add_factor"] = 2.5,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 4,
		["dex_add_factor"] = 3,
		["type"] = 2,

	},
	["9"] = {
		["quality"] = 4,
		["streng_expend_factor"] = 1.6666666666667,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 7.5,
		["cri_add_factor"] = 3,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 4.5,
		["dex_add_factor"] = 3.5,
		["type"] = 2,

	},
	["10"] = {
		["quality"] = 5,
		["streng_expend_factor"] = 2.6666666666667,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 10.5,
		["cri_add_factor"] = 4,
		["block_add_factor"] = 3,
		["agl_add_factor"] = 6,
		["dex_add_factor"] = 4.5,
		["type"] = 2,

	},
	["11"] = {
		["quality"] = 1,
		["streng_expend_factor"] = 1,
		["hp_add_factor"] = 20.5,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1,
		["agl_add_factor"] = 3,
		["dex_add_factor"] = 2,
		["type"] = 4,

	},
	["12"] = {
		["quality"] = 2,
		["streng_expend_factor"] = 1.3333333333333,
		["hp_add_factor"] = 24.5,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1.5,
		["agl_add_factor"] = 3.5,
		["dex_add_factor"] = 2,
		["type"] = 4,

	},
	["13"] = {
		["quality"] = 3,
		["streng_expend_factor"] = 2.3333333333333,
		["hp_add_factor"] = 30.5,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2.5,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 4,
		["dex_add_factor"] = 3,
		["type"] = 4,

	},
	["14"] = {
		["quality"] = 4,
		["streng_expend_factor"] = 3.6666666666667,
		["hp_add_factor"] = 38.5,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 4.5,
		["dex_add_factor"] = 3.5,
		["type"] = 4,

	},
	["15"] = {
		["quality"] = 5,
		["streng_expend_factor"] = 6,
		["hp_add_factor"] = 52.5,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 4,
		["block_add_factor"] = 3,
		["agl_add_factor"] = 6,
		["dex_add_factor"] = 4.5,
		["type"] = 4,

	},
	["16"] = {
		["quality"] = 1,
		["streng_expend_factor"] = 4,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 1,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1,
		["agl_add_factor"] = 3,
		["dex_add_factor"] = 2,
		["type"] = 5,

	},
	["17"] = {
		["quality"] = 2,
		["streng_expend_factor"] = 5.6666666666667,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 1.5,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1.5,
		["agl_add_factor"] = 3.5,
		["dex_add_factor"] = 2,
		["type"] = 5,

	},
	["18"] = {
		["quality"] = 3,
		["streng_expend_factor"] = 8.3333333333333,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 2,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2.5,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 4,
		["dex_add_factor"] = 3,
		["type"] = 5,

	},
	["19"] = {
		["quality"] = 4,
		["streng_expend_factor"] = 13.333333333333,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 2.5,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 4.5,
		["dex_add_factor"] = 3.5,
		["type"] = 5,

	},
	["20"] = {
		["quality"] = 5,
		["streng_expend_factor"] = 21.666666666667,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 3.5,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 4,
		["block_add_factor"] = 3,
		["agl_add_factor"] = 6,
		["dex_add_factor"] = 4.5,
		["type"] = 5,

	},

}
return define_streng_factor
