local define_vip = {
	["0"] = {
		["recharge_gold"] = "0",
		["privilege_desc"] = "非VIP",
		["buy_pack"] = "1",
		["streng_lv"] = "2,3",
		["challenge_num"] = "-1",
		["use_drug_add"] = "-1",
		["friends_caps_add"] = "-1",
		["sport_free_count"] = "6",
		["sport_buy_count"] = "-1",
		["dt_buy_count"] = "-1",
		["coins_ectype_count"] = "2",
		["call_starsoul"] = "1",
		["onekey_starsoul"] = "1",
		["energy_buy_count"] = "1",
		["coins_buy_count"] = "1",
		["rob_book_count"] = 10,
		["pve_buy_count"] = "1",
		["convoy_count"] = "2",
		["convoy_rob_count"] = "5",
		["convoy_truck_count"] = "2",
		["ten_sweep"] = "0",

	},
	["1"] = {
		["recharge_gold"] = "100",
		["privilege_desc"] = "1.购买VIP_1级礼包2.强化暴击后，可能会出现装备等级提高2 — 3级",
		["buy_pack"] = "17",
		["streng_lv"] = "2,3",
		["challenge_num"] = "-1",
		["use_drug_add"] = "-1",
		["friends_caps_add"] = "-1",
		["sport_free_count"] = "6",
		["sport_buy_count"] = "2",
		["dt_buy_count"] = "-1",
		["coins_ectype_count"] = "3",
		["call_starsoul"] = "1",
		["onekey_starsoul"] = "1",
		["energy_buy_count"] = "2",
		["coins_buy_count"] = "2",
		["rob_book_count"] = "10",
		["pve_buy_count"] = "2",
		["convoy_count"] = "4",
		["convoy_rob_count"] = "7",
		["convoy_truck_count"] = "3",
		["ten_sweep"] = "1",

	},
	["2"] = {
		["recharge_gold"] = "200",
		["privilege_desc"] = "1.购买VIP_2级礼包2.强化暴击后，可能会出现装备等级提高2 — 4级3.增加赛制联赛每日的免费挑战次数3次",
		["buy_pack"] = "18",
		["streng_lv"] = "2,4",
		["challenge_num"] = "3",
		["use_drug_add"] = "-1",
		["friends_caps_add"] = "-1",
		["sport_free_count"] = "6",
		["sport_buy_count"] = "3",
		["dt_buy_count"] = "-1",
		["coins_ectype_count"] = "4",
		["call_starsoul"] = "1",
		["onekey_starsoul"] = "1",
		["energy_buy_count"] = "3",
		["coins_buy_count"] = "3",
		["rob_book_count"] = "12",
		["pve_buy_count"] = "3",
		["convoy_count"] = "4",
		["convoy_rob_count"] = "8",
		["convoy_truck_count"] = "3",
		["ten_sweep"] = "1",

	},
	["3"] = {
		["recharge_gold"] = "500",
		["privilege_desc"] = "1.购买VIP_3级礼包2.强化暴击后，可能会出现装备等级提高2 — 5级3.增加赛制联赛每日的免费挑战次数4次4.增加每日使用体力药剂回复体力的次数5次",
		["buy_pack"] = "19",
		["streng_lv"] = "2,5",
		["challenge_num"] = "4",
		["use_drug_add"] = "5",
		["friends_caps_add"] = "-1",
		["sport_free_count"] = "6",
		["sport_buy_count"] = "4",
		["dt_buy_count"] = "-1",
		["coins_ectype_count"] = "5",
		["call_starsoul"] = "1",
		["onekey_starsoul"] = "1",
		["energy_buy_count"] = "4",
		["coins_buy_count"] = "4",
		["rob_book_count"] = "14",
		["pve_buy_count"] = "4",
		["convoy_count"] = "4",
		["convoy_rob_count"] = "9",
		["convoy_truck_count"] = "3",
		["ten_sweep"] = "1",

	},
	["4"] = {
		["recharge_gold"] = "1500",
		["privilege_desc"] = "1.购买VIP_4级礼包2.强化暴击后，可能会出现装备等级提高2 — 6级3.增加赛制联赛每日的免费挑战次数5次4.增加每日使用体力药剂回复体力的次数10次5.增加每日使用挑战书的次数5次",
		["buy_pack"] = "20",
		["streng_lv"] = "2,6",
		["challenge_num"] = "5",
		["use_drug_add"] = "10",
		["friends_caps_add"] = "-1",
		["sport_free_count"] = "6",
		["sport_buy_count"] = "5",
		["dt_buy_count"] = "-1",
		["coins_ectype_count"] = "6",
		["call_starsoul"] = "1",
		["onekey_starsoul"] = "1",
		["energy_buy_count"] = "5",
		["coins_buy_count"] = "5",
		["rob_book_count"] = "18",
		["pve_buy_count"] = "5",
		["convoy_count"] = "5",
		["convoy_rob_count"] = "10",
		["convoy_truck_count"] = "4",
		["ten_sweep"] = "1",

	},
	["5"] = {
		["recharge_gold"] = "3000",
		["privilege_desc"] = "1.购买VIP_5级礼包2.强化暴击后，可能会出现装备等级提高2 — 7级3.增加赛制联赛每日的免费挑战次数6次4.增加每日使用体力药剂回复体力的次数15次5.增加每日使用挑战书的次数10次6.增加好友上限5人",
		["buy_pack"] = "21",
		["streng_lv"] = "2,7",
		["challenge_num"] = "6",
		["use_drug_add"] = "15",
		["friends_caps_add"] = "5",
		["sport_free_count"] = "6",
		["sport_buy_count"] = "6",
		["dt_buy_count"] = "-1",
		["coins_ectype_count"] = "7",
		["call_starsoul"] = "1",
		["onekey_starsoul"] = "1",
		["energy_buy_count"] = "6",
		["coins_buy_count"] = "6",
		["rob_book_count"] = "24",
		["pve_buy_count"] = "6",
		["convoy_count"] = "5",
		["convoy_rob_count"] = "11",
		["convoy_truck_count"] = "4",
		["ten_sweep"] = "1",

	},
	["6"] = {
		["recharge_gold"] = "5000",
		["privilege_desc"] = "1.购买VIP_6级礼包2.强化暴击后，可能会出现装备等级提高2 — 7级3.增加赛制联赛每日的免费挑战次数7次4.增加每日使用体力药剂回复体力的次数20次5.增加每日使用挑战书的次数15次6.增加好友上限10人",
		["buy_pack"] = "22",
		["streng_lv"] = "2,8",
		["challenge_num"] = "7",
		["use_drug_add"] = "20",
		["friends_caps_add"] = "10",
		["sport_free_count"] = "6",
		["sport_buy_count"] = "7",
		["dt_buy_count"] = "-1",
		["coins_ectype_count"] = "8",
		["call_starsoul"] = "1",
		["onekey_starsoul"] = "1",
		["energy_buy_count"] = "7",
		["coins_buy_count"] = "7",
		["rob_book_count"] = "30",
		["pve_buy_count"] = "8",
		["convoy_count"] = "5",
		["convoy_rob_count"] = "12",
		["convoy_truck_count"] = "4",
		["ten_sweep"] = "1",

	},

}
return define_vip
