<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['coin_log_info'] = array(
        1 => 'Payment',
        2 => 'Payment Promotion',
        3 => 'Benefit',
        4 => 'Tutorial',
        5 => 'Market Review',
        6 => 'Sell Rune',
        7 => 'Invite',
        8 => 'Receive Letter',
        51 => 'Continue Game',
        52 => 'Rune Enchant',
        53 => 'Character Level Up',
        54 => 'Character Change Class',
        55 => 'Buy Stamina',
        56 => 'Buy Point',
        57 => 'Lotto Box',
    );

$config['process_code'] = array(
        1 => 'Login',
        2 => 'Change Nickname',
        3 => 'Payment',
        4 => 'Buy Item',
        5 => 'Buy Stamina',
        6 => 'Buy Point',
        7 => 'Lotto Box',
        8 => 'Game Start',
        9 => 'Game Finish',
        10 => 'Tutorial Success',
        11 => 'Continue Game',
        12 => 'Market Review',
        13 => 'Character Level Up',
        14 => 'Rune Equipment',
        15 => 'Rune Enchant',
        16 => 'Sell Rune',
        17 => 'Add Friend',
        18 => 'Delete Friend',
        19 => 'Accept Friend',
        20 => 'Invite Friend',
        21 => 'Send Letter',
        22 => 'Receive Letter',
        23 => 'Click Banner',
        24 => 'Add Recommender',
    );