// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InfiniteResult_Ack.proto

#ifndef PROTOBUF_InfiniteResult_5fAck_2eproto__INCLUDED
#define PROTOBUF_InfiniteResult_5fAck_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_InfiniteResult_5fAck_2eproto();
void protobuf_AssignDesc_InfiniteResult_5fAck_2eproto();
void protobuf_ShutdownFile_InfiniteResult_5fAck_2eproto();

class InfiniteResult_Ack;

// ===================================================================

class InfiniteResult_Ack : public ::google::protobuf::Message {
 public:
  InfiniteResult_Ack();
  virtual ~InfiniteResult_Ack();

  InfiniteResult_Ack(const InfiniteResult_Ack& from);

  inline InfiniteResult_Ack& operator=(const InfiniteResult_Ack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InfiniteResult_Ack& default_instance();

  void Swap(InfiniteResult_Ack* other);

  // implements Message ----------------------------------------------

  InfiniteResult_Ack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InfiniteResult_Ack& from);
  void MergeFrom(const InfiniteResult_Ack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string msgInfo = 1;
  inline bool has_msginfo() const;
  inline void clear_msginfo();
  static const int kMsgInfoFieldNumber = 1;
  inline const ::std::string& msginfo() const;
  inline void set_msginfo(const ::std::string& value);
  inline void set_msginfo(const char* value);
  inline void set_msginfo(const char* value, size_t size);
  inline ::std::string* mutable_msginfo();
  inline ::std::string* release_msginfo();
  inline void set_allocated_msginfo(::std::string* msginfo);

  // optional int32 allmax = 2;
  inline bool has_allmax() const;
  inline void clear_allmax();
  static const int kAllmaxFieldNumber = 2;
  inline ::google::protobuf::int32 allmax() const;
  inline void set_allmax(::google::protobuf::int32 value);

  // optional int32 weekmax = 3;
  inline bool has_weekmax() const;
  inline void clear_weekmax();
  static const int kWeekmaxFieldNumber = 3;
  inline ::google::protobuf::int32 weekmax() const;
  inline void set_weekmax(::google::protobuf::int32 value);

  // optional int32 maxtype = 4;
  inline bool has_maxtype() const;
  inline void clear_maxtype();
  static const int kMaxtypeFieldNumber = 4;
  inline ::google::protobuf::int32 maxtype() const;
  inline void set_maxtype(::google::protobuf::int32 value);

  // optional int32 crowntype = 5;
  inline bool has_crowntype() const;
  inline void clear_crowntype();
  static const int kCrowntypeFieldNumber = 5;
  inline ::google::protobuf::int32 crowntype() const;
  inline void set_crowntype(::google::protobuf::int32 value);

  // optional int32 acktime = 6;
  inline bool has_acktime() const;
  inline void clear_acktime();
  static const int kAcktimeFieldNumber = 6;
  inline ::google::protobuf::int32 acktime() const;
  inline void set_acktime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protobuf.InfiniteResult_Ack)
 private:
  inline void set_has_msginfo();
  inline void clear_has_msginfo();
  inline void set_has_allmax();
  inline void clear_has_allmax();
  inline void set_has_weekmax();
  inline void clear_has_weekmax();
  inline void set_has_maxtype();
  inline void clear_has_maxtype();
  inline void set_has_crowntype();
  inline void clear_has_crowntype();
  inline void set_has_acktime();
  inline void clear_has_acktime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* msginfo_;
  ::google::protobuf::int32 allmax_;
  ::google::protobuf::int32 weekmax_;
  ::google::protobuf::int32 maxtype_;
  ::google::protobuf::int32 crowntype_;
  ::google::protobuf::int32 acktime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_InfiniteResult_5fAck_2eproto();
  friend void protobuf_AssignDesc_InfiniteResult_5fAck_2eproto();
  friend void protobuf_ShutdownFile_InfiniteResult_5fAck_2eproto();

  void InitAsDefaultInstance();
  static InfiniteResult_Ack* default_instance_;
};
// ===================================================================


// ===================================================================

// InfiniteResult_Ack

// optional string msgInfo = 1;
inline bool InfiniteResult_Ack::has_msginfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InfiniteResult_Ack::set_has_msginfo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InfiniteResult_Ack::clear_has_msginfo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InfiniteResult_Ack::clear_msginfo() {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    msginfo_->clear();
  }
  clear_has_msginfo();
}
inline const ::std::string& InfiniteResult_Ack::msginfo() const {
  return *msginfo_;
}
inline void InfiniteResult_Ack::set_msginfo(const ::std::string& value) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(value);
}
inline void InfiniteResult_Ack::set_msginfo(const char* value) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(value);
}
inline void InfiniteResult_Ack::set_msginfo(const char* value, size_t size) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* InfiniteResult_Ack::mutable_msginfo() {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  return msginfo_;
}
inline ::std::string* InfiniteResult_Ack::release_msginfo() {
  clear_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msginfo_;
    msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void InfiniteResult_Ack::set_allocated_msginfo(::std::string* msginfo) {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    delete msginfo_;
  }
  if (msginfo) {
    set_has_msginfo();
    msginfo_ = msginfo;
  } else {
    clear_has_msginfo();
    msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 allmax = 2;
inline bool InfiniteResult_Ack::has_allmax() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void InfiniteResult_Ack::set_has_allmax() {
  _has_bits_[0] |= 0x00000002u;
}
inline void InfiniteResult_Ack::clear_has_allmax() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void InfiniteResult_Ack::clear_allmax() {
  allmax_ = 0;
  clear_has_allmax();
}
inline ::google::protobuf::int32 InfiniteResult_Ack::allmax() const {
  return allmax_;
}
inline void InfiniteResult_Ack::set_allmax(::google::protobuf::int32 value) {
  set_has_allmax();
  allmax_ = value;
}

// optional int32 weekmax = 3;
inline bool InfiniteResult_Ack::has_weekmax() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void InfiniteResult_Ack::set_has_weekmax() {
  _has_bits_[0] |= 0x00000004u;
}
inline void InfiniteResult_Ack::clear_has_weekmax() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void InfiniteResult_Ack::clear_weekmax() {
  weekmax_ = 0;
  clear_has_weekmax();
}
inline ::google::protobuf::int32 InfiniteResult_Ack::weekmax() const {
  return weekmax_;
}
inline void InfiniteResult_Ack::set_weekmax(::google::protobuf::int32 value) {
  set_has_weekmax();
  weekmax_ = value;
}

// optional int32 maxtype = 4;
inline bool InfiniteResult_Ack::has_maxtype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void InfiniteResult_Ack::set_has_maxtype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void InfiniteResult_Ack::clear_has_maxtype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void InfiniteResult_Ack::clear_maxtype() {
  maxtype_ = 0;
  clear_has_maxtype();
}
inline ::google::protobuf::int32 InfiniteResult_Ack::maxtype() const {
  return maxtype_;
}
inline void InfiniteResult_Ack::set_maxtype(::google::protobuf::int32 value) {
  set_has_maxtype();
  maxtype_ = value;
}

// optional int32 crowntype = 5;
inline bool InfiniteResult_Ack::has_crowntype() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void InfiniteResult_Ack::set_has_crowntype() {
  _has_bits_[0] |= 0x00000010u;
}
inline void InfiniteResult_Ack::clear_has_crowntype() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void InfiniteResult_Ack::clear_crowntype() {
  crowntype_ = 0;
  clear_has_crowntype();
}
inline ::google::protobuf::int32 InfiniteResult_Ack::crowntype() const {
  return crowntype_;
}
inline void InfiniteResult_Ack::set_crowntype(::google::protobuf::int32 value) {
  set_has_crowntype();
  crowntype_ = value;
}

// optional int32 acktime = 6;
inline bool InfiniteResult_Ack::has_acktime() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void InfiniteResult_Ack::set_has_acktime() {
  _has_bits_[0] |= 0x00000020u;
}
inline void InfiniteResult_Ack::clear_has_acktime() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void InfiniteResult_Ack::clear_acktime() {
  acktime_ = 0;
  clear_has_acktime();
}
inline ::google::protobuf::int32 InfiniteResult_Ack::acktime() const {
  return acktime_;
}
inline void InfiniteResult_Ack::set_acktime(::google::protobuf::int32 value) {
  set_has_acktime();
  acktime_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_InfiniteResult_5fAck_2eproto__INCLUDED
