// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SelectFriend_Ack.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SelectFriend_Ack.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* SelectFriend_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SelectFriend_Ack_reflection_ = NULL;
const ::google::protobuf::Descriptor* SelectFriend_Ack_FriendList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SelectFriend_Ack_FriendList_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SelectFriend_5fAck_2eproto() {
  protobuf_AddDesc_SelectFriend_5fAck_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SelectFriend_Ack.proto");
  GOOGLE_CHECK(file != NULL);
  SelectFriend_Ack_descriptor_ = file->message_type(0);
  static const int SelectFriend_Ack_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack, msginfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack, friendlist_),
  };
  SelectFriend_Ack_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SelectFriend_Ack_descriptor_,
      SelectFriend_Ack::default_instance_,
      SelectFriend_Ack_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SelectFriend_Ack));
  SelectFriend_Ack_FriendList_descriptor_ = SelectFriend_Ack_descriptor_->nested_type(0);
  static const int SelectFriend_Ack_FriendList_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack_FriendList, nickname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack_FriendList, level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack_FriendList, score_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack_FriendList, distance_),
  };
  SelectFriend_Ack_FriendList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SelectFriend_Ack_FriendList_descriptor_,
      SelectFriend_Ack_FriendList::default_instance_,
      SelectFriend_Ack_FriendList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack_FriendList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectFriend_Ack_FriendList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SelectFriend_Ack_FriendList));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SelectFriend_5fAck_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SelectFriend_Ack_descriptor_, &SelectFriend_Ack::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SelectFriend_Ack_FriendList_descriptor_, &SelectFriend_Ack_FriendList::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SelectFriend_5fAck_2eproto() {
  delete SelectFriend_Ack::default_instance_;
  delete SelectFriend_Ack_reflection_;
  delete SelectFriend_Ack_FriendList::default_instance_;
  delete SelectFriend_Ack_FriendList_reflection_;
}

void protobuf_AddDesc_SelectFriend_5fAck_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026SelectFriend_Ack.proto\022\010protobuf\"\256\001\n\020S"
    "electFriend_Ack\022\017\n\007msgInfo\030\001 \001(\t\0229\n\nfrie"
    "ndList\030\002 \003(\0132%.protobuf.SelectFriend_Ack"
    ".FriendList\032N\n\nFriendList\022\020\n\010nickname\030\001 "
    "\001(\005\022\r\n\005level\030\002 \001(\005\022\r\n\005score\030\003 \001(\005\022\020\n\010dis"
    "tance\030\004 \001(\005", 211);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SelectFriend_Ack.proto", &protobuf_RegisterTypes);
  SelectFriend_Ack::default_instance_ = new SelectFriend_Ack();
  SelectFriend_Ack_FriendList::default_instance_ = new SelectFriend_Ack_FriendList();
  SelectFriend_Ack::default_instance_->InitAsDefaultInstance();
  SelectFriend_Ack_FriendList::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SelectFriend_5fAck_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SelectFriend_5fAck_2eproto {
  StaticDescriptorInitializer_SelectFriend_5fAck_2eproto() {
    protobuf_AddDesc_SelectFriend_5fAck_2eproto();
  }
} static_descriptor_initializer_SelectFriend_5fAck_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int SelectFriend_Ack_FriendList::kNicknameFieldNumber;
const int SelectFriend_Ack_FriendList::kLevelFieldNumber;
const int SelectFriend_Ack_FriendList::kScoreFieldNumber;
const int SelectFriend_Ack_FriendList::kDistanceFieldNumber;
#endif  // !_MSC_VER

SelectFriend_Ack_FriendList::SelectFriend_Ack_FriendList()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SelectFriend_Ack_FriendList::InitAsDefaultInstance() {
}

SelectFriend_Ack_FriendList::SelectFriend_Ack_FriendList(const SelectFriend_Ack_FriendList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SelectFriend_Ack_FriendList::SharedCtor() {
  _cached_size_ = 0;
  nickname_ = 0;
  level_ = 0;
  score_ = 0;
  distance_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SelectFriend_Ack_FriendList::~SelectFriend_Ack_FriendList() {
  SharedDtor();
}

void SelectFriend_Ack_FriendList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SelectFriend_Ack_FriendList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SelectFriend_Ack_FriendList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SelectFriend_Ack_FriendList_descriptor_;
}

const SelectFriend_Ack_FriendList& SelectFriend_Ack_FriendList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SelectFriend_5fAck_2eproto();
  return *default_instance_;
}

SelectFriend_Ack_FriendList* SelectFriend_Ack_FriendList::default_instance_ = NULL;

SelectFriend_Ack_FriendList* SelectFriend_Ack_FriendList::New() const {
  return new SelectFriend_Ack_FriendList;
}

void SelectFriend_Ack_FriendList::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    nickname_ = 0;
    level_ = 0;
    score_ = 0;
    distance_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SelectFriend_Ack_FriendList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 nickname = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nickname_)));
          set_has_nickname();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_level;
        break;
      }

      // optional int32 level = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_level:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &level_)));
          set_has_level();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_score;
        break;
      }

      // optional int32 score = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_score:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &score_)));
          set_has_score();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_distance;
        break;
      }

      // optional int32 distance = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_distance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &distance_)));
          set_has_distance();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SelectFriend_Ack_FriendList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 nickname = 1;
  if (has_nickname()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->nickname(), output);
  }

  // optional int32 level = 2;
  if (has_level()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->level(), output);
  }

  // optional int32 score = 3;
  if (has_score()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->score(), output);
  }

  // optional int32 distance = 4;
  if (has_distance()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->distance(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SelectFriend_Ack_FriendList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 nickname = 1;
  if (has_nickname()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->nickname(), target);
  }

  // optional int32 level = 2;
  if (has_level()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->level(), target);
  }

  // optional int32 score = 3;
  if (has_score()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->score(), target);
  }

  // optional int32 distance = 4;
  if (has_distance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->distance(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SelectFriend_Ack_FriendList::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 nickname = 1;
    if (has_nickname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nickname());
    }

    // optional int32 level = 2;
    if (has_level()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->level());
    }

    // optional int32 score = 3;
    if (has_score()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->score());
    }

    // optional int32 distance = 4;
    if (has_distance()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->distance());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SelectFriend_Ack_FriendList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SelectFriend_Ack_FriendList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SelectFriend_Ack_FriendList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SelectFriend_Ack_FriendList::MergeFrom(const SelectFriend_Ack_FriendList& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_nickname()) {
      set_nickname(from.nickname());
    }
    if (from.has_level()) {
      set_level(from.level());
    }
    if (from.has_score()) {
      set_score(from.score());
    }
    if (from.has_distance()) {
      set_distance(from.distance());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SelectFriend_Ack_FriendList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SelectFriend_Ack_FriendList::CopyFrom(const SelectFriend_Ack_FriendList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SelectFriend_Ack_FriendList::IsInitialized() const {

  return true;
}

void SelectFriend_Ack_FriendList::Swap(SelectFriend_Ack_FriendList* other) {
  if (other != this) {
    std::swap(nickname_, other->nickname_);
    std::swap(level_, other->level_);
    std::swap(score_, other->score_);
    std::swap(distance_, other->distance_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SelectFriend_Ack_FriendList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SelectFriend_Ack_FriendList_descriptor_;
  metadata.reflection = SelectFriend_Ack_FriendList_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SelectFriend_Ack::kMsgInfoFieldNumber;
const int SelectFriend_Ack::kFriendListFieldNumber;
#endif  // !_MSC_VER

SelectFriend_Ack::SelectFriend_Ack()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SelectFriend_Ack::InitAsDefaultInstance() {
}

SelectFriend_Ack::SelectFriend_Ack(const SelectFriend_Ack& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SelectFriend_Ack::SharedCtor() {
  _cached_size_ = 0;
  msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SelectFriend_Ack::~SelectFriend_Ack() {
  SharedDtor();
}

void SelectFriend_Ack::SharedDtor() {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    delete msginfo_;
  }
  if (this != default_instance_) {
  }
}

void SelectFriend_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SelectFriend_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SelectFriend_Ack_descriptor_;
}

const SelectFriend_Ack& SelectFriend_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SelectFriend_5fAck_2eproto();
  return *default_instance_;
}

SelectFriend_Ack* SelectFriend_Ack::default_instance_ = NULL;

SelectFriend_Ack* SelectFriend_Ack::New() const {
  return new SelectFriend_Ack;
}

void SelectFriend_Ack::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_msginfo()) {
      if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
        msginfo_->clear();
      }
    }
  }
  friendlist_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SelectFriend_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string msgInfo = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msginfo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->msginfo().data(), this->msginfo().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_friendList;
        break;
      }

      // repeated .protobuf.SelectFriend_Ack.FriendList friendList = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_friendList:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_friendlist()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_friendList;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SelectFriend_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string msgInfo = 1;
  if (has_msginfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msginfo().data(), this->msginfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->msginfo(), output);
  }

  // repeated .protobuf.SelectFriend_Ack.FriendList friendList = 2;
  for (int i = 0; i < this->friendlist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->friendlist(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SelectFriend_Ack::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string msgInfo = 1;
  if (has_msginfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msginfo().data(), this->msginfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msginfo(), target);
  }

  // repeated .protobuf.SelectFriend_Ack.FriendList friendList = 2;
  for (int i = 0; i < this->friendlist_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->friendlist(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SelectFriend_Ack::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string msgInfo = 1;
    if (has_msginfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msginfo());
    }

  }
  // repeated .protobuf.SelectFriend_Ack.FriendList friendList = 2;
  total_size += 1 * this->friendlist_size();
  for (int i = 0; i < this->friendlist_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->friendlist(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SelectFriend_Ack::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SelectFriend_Ack* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SelectFriend_Ack*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SelectFriend_Ack::MergeFrom(const SelectFriend_Ack& from) {
  GOOGLE_CHECK_NE(&from, this);
  friendlist_.MergeFrom(from.friendlist_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msginfo()) {
      set_msginfo(from.msginfo());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SelectFriend_Ack::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SelectFriend_Ack::CopyFrom(const SelectFriend_Ack& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SelectFriend_Ack::IsInitialized() const {

  return true;
}

void SelectFriend_Ack::Swap(SelectFriend_Ack* other) {
  if (other != this) {
    std::swap(msginfo_, other->msginfo_);
    friendlist_.Swap(&other->friendlist_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SelectFriend_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SelectFriend_Ack_descriptor_;
  metadata.reflection = SelectFriend_Ack_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)
