// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StageList_Ack.proto

#ifndef PROTOBUF_StageList_5fAck_2eproto__INCLUDED
#define PROTOBUF_StageList_5fAck_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_StageList_5fAck_2eproto();
void protobuf_AssignDesc_StageList_5fAck_2eproto();
void protobuf_ShutdownFile_StageList_5fAck_2eproto();

class StageList_Ack;
class StageList_Ack_StageList;

// ===================================================================

class StageList_Ack_StageList : public ::google::protobuf::Message {
 public:
  StageList_Ack_StageList();
  virtual ~StageList_Ack_StageList();

  StageList_Ack_StageList(const StageList_Ack_StageList& from);

  inline StageList_Ack_StageList& operator=(const StageList_Ack_StageList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StageList_Ack_StageList& default_instance();

  void Swap(StageList_Ack_StageList* other);

  // implements Message ----------------------------------------------

  StageList_Ack_StageList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StageList_Ack_StageList& from);
  void MergeFrom(const StageList_Ack_StageList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 stageId = 1;
  inline bool has_stageid() const;
  inline void clear_stageid();
  static const int kStageIdFieldNumber = 1;
  inline ::google::protobuf::int32 stageid() const;
  inline void set_stageid(::google::protobuf::int32 value);

  // optional int32 star = 2;
  inline bool has_star() const;
  inline void clear_star();
  static const int kStarFieldNumber = 2;
  inline ::google::protobuf::int32 star() const;
  inline void set_star(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protobuf.StageList_Ack.StageList)
 private:
  inline void set_has_stageid();
  inline void clear_has_stageid();
  inline void set_has_star();
  inline void clear_has_star();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 stageid_;
  ::google::protobuf::int32 star_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_StageList_5fAck_2eproto();
  friend void protobuf_AssignDesc_StageList_5fAck_2eproto();
  friend void protobuf_ShutdownFile_StageList_5fAck_2eproto();

  void InitAsDefaultInstance();
  static StageList_Ack_StageList* default_instance_;
};
// -------------------------------------------------------------------

class StageList_Ack : public ::google::protobuf::Message {
 public:
  StageList_Ack();
  virtual ~StageList_Ack();

  StageList_Ack(const StageList_Ack& from);

  inline StageList_Ack& operator=(const StageList_Ack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StageList_Ack& default_instance();

  void Swap(StageList_Ack* other);

  // implements Message ----------------------------------------------

  StageList_Ack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StageList_Ack& from);
  void MergeFrom(const StageList_Ack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef StageList_Ack_StageList StageList;

  // accessors -------------------------------------------------------

  // optional string msgInfo = 1;
  inline bool has_msginfo() const;
  inline void clear_msginfo();
  static const int kMsgInfoFieldNumber = 1;
  inline const ::std::string& msginfo() const;
  inline void set_msginfo(const ::std::string& value);
  inline void set_msginfo(const char* value);
  inline void set_msginfo(const char* value, size_t size);
  inline ::std::string* mutable_msginfo();
  inline ::std::string* release_msginfo();
  inline void set_allocated_msginfo(::std::string* msginfo);

  // optional int32 sumStar = 2;
  inline bool has_sumstar() const;
  inline void clear_sumstar();
  static const int kSumStarFieldNumber = 2;
  inline ::google::protobuf::int32 sumstar() const;
  inline void set_sumstar(::google::protobuf::int32 value);

  // repeated .protobuf.StageList_Ack.StageList stageList = 3;
  inline int stagelist_size() const;
  inline void clear_stagelist();
  static const int kStageListFieldNumber = 3;
  inline const ::protobuf::StageList_Ack_StageList& stagelist(int index) const;
  inline ::protobuf::StageList_Ack_StageList* mutable_stagelist(int index);
  inline ::protobuf::StageList_Ack_StageList* add_stagelist();
  inline const ::google::protobuf::RepeatedPtrField< ::protobuf::StageList_Ack_StageList >&
      stagelist() const;
  inline ::google::protobuf::RepeatedPtrField< ::protobuf::StageList_Ack_StageList >*
      mutable_stagelist();

  // optional int32 newStage = 4;
  inline bool has_newstage() const;
  inline void clear_newstage();
  static const int kNewStageFieldNumber = 4;
  inline ::google::protobuf::int32 newstage() const;
  inline void set_newstage(::google::protobuf::int32 value);

  // optional int32 acktime = 5;
  inline bool has_acktime() const;
  inline void clear_acktime();
  static const int kAcktimeFieldNumber = 5;
  inline ::google::protobuf::int32 acktime() const;
  inline void set_acktime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protobuf.StageList_Ack)
 private:
  inline void set_has_msginfo();
  inline void clear_has_msginfo();
  inline void set_has_sumstar();
  inline void clear_has_sumstar();
  inline void set_has_newstage();
  inline void clear_has_newstage();
  inline void set_has_acktime();
  inline void clear_has_acktime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* msginfo_;
  ::google::protobuf::RepeatedPtrField< ::protobuf::StageList_Ack_StageList > stagelist_;
  ::google::protobuf::int32 sumstar_;
  ::google::protobuf::int32 newstage_;
  ::google::protobuf::int32 acktime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_StageList_5fAck_2eproto();
  friend void protobuf_AssignDesc_StageList_5fAck_2eproto();
  friend void protobuf_ShutdownFile_StageList_5fAck_2eproto();

  void InitAsDefaultInstance();
  static StageList_Ack* default_instance_;
};
// ===================================================================


// ===================================================================

// StageList_Ack_StageList

// optional int32 stageId = 1;
inline bool StageList_Ack_StageList::has_stageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StageList_Ack_StageList::set_has_stageid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StageList_Ack_StageList::clear_has_stageid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StageList_Ack_StageList::clear_stageid() {
  stageid_ = 0;
  clear_has_stageid();
}
inline ::google::protobuf::int32 StageList_Ack_StageList::stageid() const {
  return stageid_;
}
inline void StageList_Ack_StageList::set_stageid(::google::protobuf::int32 value) {
  set_has_stageid();
  stageid_ = value;
}

// optional int32 star = 2;
inline bool StageList_Ack_StageList::has_star() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StageList_Ack_StageList::set_has_star() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StageList_Ack_StageList::clear_has_star() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StageList_Ack_StageList::clear_star() {
  star_ = 0;
  clear_has_star();
}
inline ::google::protobuf::int32 StageList_Ack_StageList::star() const {
  return star_;
}
inline void StageList_Ack_StageList::set_star(::google::protobuf::int32 value) {
  set_has_star();
  star_ = value;
}

// -------------------------------------------------------------------

// StageList_Ack

// optional string msgInfo = 1;
inline bool StageList_Ack::has_msginfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StageList_Ack::set_has_msginfo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StageList_Ack::clear_has_msginfo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StageList_Ack::clear_msginfo() {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    msginfo_->clear();
  }
  clear_has_msginfo();
}
inline const ::std::string& StageList_Ack::msginfo() const {
  return *msginfo_;
}
inline void StageList_Ack::set_msginfo(const ::std::string& value) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(value);
}
inline void StageList_Ack::set_msginfo(const char* value) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(value);
}
inline void StageList_Ack::set_msginfo(const char* value, size_t size) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* StageList_Ack::mutable_msginfo() {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  return msginfo_;
}
inline ::std::string* StageList_Ack::release_msginfo() {
  clear_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msginfo_;
    msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void StageList_Ack::set_allocated_msginfo(::std::string* msginfo) {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    delete msginfo_;
  }
  if (msginfo) {
    set_has_msginfo();
    msginfo_ = msginfo;
  } else {
    clear_has_msginfo();
    msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 sumStar = 2;
inline bool StageList_Ack::has_sumstar() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StageList_Ack::set_has_sumstar() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StageList_Ack::clear_has_sumstar() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StageList_Ack::clear_sumstar() {
  sumstar_ = 0;
  clear_has_sumstar();
}
inline ::google::protobuf::int32 StageList_Ack::sumstar() const {
  return sumstar_;
}
inline void StageList_Ack::set_sumstar(::google::protobuf::int32 value) {
  set_has_sumstar();
  sumstar_ = value;
}

// repeated .protobuf.StageList_Ack.StageList stageList = 3;
inline int StageList_Ack::stagelist_size() const {
  return stagelist_.size();
}
inline void StageList_Ack::clear_stagelist() {
  stagelist_.Clear();
}
inline const ::protobuf::StageList_Ack_StageList& StageList_Ack::stagelist(int index) const {
  return stagelist_.Get(index);
}
inline ::protobuf::StageList_Ack_StageList* StageList_Ack::mutable_stagelist(int index) {
  return stagelist_.Mutable(index);
}
inline ::protobuf::StageList_Ack_StageList* StageList_Ack::add_stagelist() {
  return stagelist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protobuf::StageList_Ack_StageList >&
StageList_Ack::stagelist() const {
  return stagelist_;
}
inline ::google::protobuf::RepeatedPtrField< ::protobuf::StageList_Ack_StageList >*
StageList_Ack::mutable_stagelist() {
  return &stagelist_;
}

// optional int32 newStage = 4;
inline bool StageList_Ack::has_newstage() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void StageList_Ack::set_has_newstage() {
  _has_bits_[0] |= 0x00000008u;
}
inline void StageList_Ack::clear_has_newstage() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void StageList_Ack::clear_newstage() {
  newstage_ = 0;
  clear_has_newstage();
}
inline ::google::protobuf::int32 StageList_Ack::newstage() const {
  return newstage_;
}
inline void StageList_Ack::set_newstage(::google::protobuf::int32 value) {
  set_has_newstage();
  newstage_ = value;
}

// optional int32 acktime = 5;
inline bool StageList_Ack::has_acktime() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void StageList_Ack::set_has_acktime() {
  _has_bits_[0] |= 0x00000010u;
}
inline void StageList_Ack::clear_has_acktime() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void StageList_Ack::clear_acktime() {
  acktime_ = 0;
  clear_has_acktime();
}
inline ::google::protobuf::int32 StageList_Ack::acktime() const {
  return acktime_;
}
inline void StageList_Ack::set_acktime(::google::protobuf::int32 value) {
  set_has_acktime();
  acktime_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_StageList_5fAck_2eproto__INCLUDED
