// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StageResult_Ack.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "StageResult_Ack.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* StageResult_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StageResult_Ack_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_StageResult_5fAck_2eproto() {
  protobuf_AddDesc_StageResult_5fAck_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "StageResult_Ack.proto");
  GOOGLE_CHECK(file != NULL);
  StageResult_Ack_descriptor_ = file->message_type(0);
  static const int StageResult_Ack_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, msginfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, allmax_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, weekmax_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, maxtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, crowntype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, coin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, diamond_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, isfirst_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, acktime_),
  };
  StageResult_Ack_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StageResult_Ack_descriptor_,
      StageResult_Ack::default_instance_,
      StageResult_Ack_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StageResult_Ack, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StageResult_Ack));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_StageResult_5fAck_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StageResult_Ack_descriptor_, &StageResult_Ack::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_StageResult_5fAck_2eproto() {
  delete StageResult_Ack::default_instance_;
  delete StageResult_Ack_reflection_;
}

void protobuf_AddDesc_StageResult_5fAck_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025StageResult_Ack.proto\022\010protobuf\"\250\001\n\017St"
    "ageResult_Ack\022\017\n\007msgInfo\030\001 \001(\t\022\016\n\006allmax"
    "\030\002 \001(\005\022\017\n\007weekmax\030\003 \001(\005\022\017\n\007maxtype\030\004 \001(\005"
    "\022\021\n\tcrowntype\030\005 \001(\005\022\014\n\004coin\030\006 \001(\005\022\017\n\007dia"
    "mond\030\007 \001(\005\022\017\n\007isFirst\030\010 \001(\010\022\017\n\007acktime\030\t"
    " \001(\005", 204);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "StageResult_Ack.proto", &protobuf_RegisterTypes);
  StageResult_Ack::default_instance_ = new StageResult_Ack();
  StageResult_Ack::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_StageResult_5fAck_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_StageResult_5fAck_2eproto {
  StaticDescriptorInitializer_StageResult_5fAck_2eproto() {
    protobuf_AddDesc_StageResult_5fAck_2eproto();
  }
} static_descriptor_initializer_StageResult_5fAck_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int StageResult_Ack::kMsgInfoFieldNumber;
const int StageResult_Ack::kAllmaxFieldNumber;
const int StageResult_Ack::kWeekmaxFieldNumber;
const int StageResult_Ack::kMaxtypeFieldNumber;
const int StageResult_Ack::kCrowntypeFieldNumber;
const int StageResult_Ack::kCoinFieldNumber;
const int StageResult_Ack::kDiamondFieldNumber;
const int StageResult_Ack::kIsFirstFieldNumber;
const int StageResult_Ack::kAcktimeFieldNumber;
#endif  // !_MSC_VER

StageResult_Ack::StageResult_Ack()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void StageResult_Ack::InitAsDefaultInstance() {
}

StageResult_Ack::StageResult_Ack(const StageResult_Ack& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void StageResult_Ack::SharedCtor() {
  _cached_size_ = 0;
  msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  allmax_ = 0;
  weekmax_ = 0;
  maxtype_ = 0;
  crowntype_ = 0;
  coin_ = 0;
  diamond_ = 0;
  isfirst_ = false;
  acktime_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StageResult_Ack::~StageResult_Ack() {
  SharedDtor();
}

void StageResult_Ack::SharedDtor() {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    delete msginfo_;
  }
  if (this != default_instance_) {
  }
}

void StageResult_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StageResult_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StageResult_Ack_descriptor_;
}

const StageResult_Ack& StageResult_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StageResult_5fAck_2eproto();
  return *default_instance_;
}

StageResult_Ack* StageResult_Ack::default_instance_ = NULL;

StageResult_Ack* StageResult_Ack::New() const {
  return new StageResult_Ack;
}

void StageResult_Ack::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_msginfo()) {
      if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
        msginfo_->clear();
      }
    }
    allmax_ = 0;
    weekmax_ = 0;
    maxtype_ = 0;
    crowntype_ = 0;
    coin_ = 0;
    diamond_ = 0;
    isfirst_ = false;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    acktime_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StageResult_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string msgInfo = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msginfo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->msginfo().data(), this->msginfo().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_allmax;
        break;
      }

      // optional int32 allmax = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_allmax:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &allmax_)));
          set_has_allmax();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_weekmax;
        break;
      }

      // optional int32 weekmax = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_weekmax:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &weekmax_)));
          set_has_weekmax();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_maxtype;
        break;
      }

      // optional int32 maxtype = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_maxtype:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &maxtype_)));
          set_has_maxtype();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_crowntype;
        break;
      }

      // optional int32 crowntype = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_crowntype:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &crowntype_)));
          set_has_crowntype();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_coin;
        break;
      }

      // optional int32 coin = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_coin:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &coin_)));
          set_has_coin();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_diamond;
        break;
      }

      // optional int32 diamond = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_diamond:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &diamond_)));
          set_has_diamond();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_isFirst;
        break;
      }

      // optional bool isFirst = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isFirst:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isfirst_)));
          set_has_isfirst();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_acktime;
        break;
      }

      // optional int32 acktime = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_acktime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &acktime_)));
          set_has_acktime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void StageResult_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string msgInfo = 1;
  if (has_msginfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msginfo().data(), this->msginfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->msginfo(), output);
  }

  // optional int32 allmax = 2;
  if (has_allmax()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->allmax(), output);
  }

  // optional int32 weekmax = 3;
  if (has_weekmax()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->weekmax(), output);
  }

  // optional int32 maxtype = 4;
  if (has_maxtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->maxtype(), output);
  }

  // optional int32 crowntype = 5;
  if (has_crowntype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->crowntype(), output);
  }

  // optional int32 coin = 6;
  if (has_coin()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->coin(), output);
  }

  // optional int32 diamond = 7;
  if (has_diamond()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->diamond(), output);
  }

  // optional bool isFirst = 8;
  if (has_isfirst()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->isfirst(), output);
  }

  // optional int32 acktime = 9;
  if (has_acktime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->acktime(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* StageResult_Ack::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string msgInfo = 1;
  if (has_msginfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msginfo().data(), this->msginfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msginfo(), target);
  }

  // optional int32 allmax = 2;
  if (has_allmax()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->allmax(), target);
  }

  // optional int32 weekmax = 3;
  if (has_weekmax()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->weekmax(), target);
  }

  // optional int32 maxtype = 4;
  if (has_maxtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->maxtype(), target);
  }

  // optional int32 crowntype = 5;
  if (has_crowntype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->crowntype(), target);
  }

  // optional int32 coin = 6;
  if (has_coin()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->coin(), target);
  }

  // optional int32 diamond = 7;
  if (has_diamond()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->diamond(), target);
  }

  // optional bool isFirst = 8;
  if (has_isfirst()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->isfirst(), target);
  }

  // optional int32 acktime = 9;
  if (has_acktime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->acktime(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int StageResult_Ack::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string msgInfo = 1;
    if (has_msginfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msginfo());
    }

    // optional int32 allmax = 2;
    if (has_allmax()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->allmax());
    }

    // optional int32 weekmax = 3;
    if (has_weekmax()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->weekmax());
    }

    // optional int32 maxtype = 4;
    if (has_maxtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->maxtype());
    }

    // optional int32 crowntype = 5;
    if (has_crowntype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->crowntype());
    }

    // optional int32 coin = 6;
    if (has_coin()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->coin());
    }

    // optional int32 diamond = 7;
    if (has_diamond()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->diamond());
    }

    // optional bool isFirst = 8;
    if (has_isfirst()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional int32 acktime = 9;
    if (has_acktime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->acktime());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StageResult_Ack::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StageResult_Ack* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StageResult_Ack*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StageResult_Ack::MergeFrom(const StageResult_Ack& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msginfo()) {
      set_msginfo(from.msginfo());
    }
    if (from.has_allmax()) {
      set_allmax(from.allmax());
    }
    if (from.has_weekmax()) {
      set_weekmax(from.weekmax());
    }
    if (from.has_maxtype()) {
      set_maxtype(from.maxtype());
    }
    if (from.has_crowntype()) {
      set_crowntype(from.crowntype());
    }
    if (from.has_coin()) {
      set_coin(from.coin());
    }
    if (from.has_diamond()) {
      set_diamond(from.diamond());
    }
    if (from.has_isfirst()) {
      set_isfirst(from.isfirst());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_acktime()) {
      set_acktime(from.acktime());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StageResult_Ack::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StageResult_Ack::CopyFrom(const StageResult_Ack& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StageResult_Ack::IsInitialized() const {

  return true;
}

void StageResult_Ack::Swap(StageResult_Ack* other) {
  if (other != this) {
    std::swap(msginfo_, other->msginfo_);
    std::swap(allmax_, other->allmax_);
    std::swap(weekmax_, other->weekmax_);
    std::swap(maxtype_, other->maxtype_);
    std::swap(crowntype_, other->crowntype_);
    std::swap(coin_, other->coin_);
    std::swap(diamond_, other->diamond_);
    std::swap(isfirst_, other->isfirst_);
    std::swap(acktime_, other->acktime_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StageResult_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StageResult_Ack_descriptor_;
  metadata.reflection = StageResult_Ack_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)
