// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaskCount_Ack.proto

#ifndef PROTOBUF_TaskCount_5fAck_2eproto__INCLUDED
#define PROTOBUF_TaskCount_5fAck_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TaskCount_5fAck_2eproto();
void protobuf_AssignDesc_TaskCount_5fAck_2eproto();
void protobuf_ShutdownFile_TaskCount_5fAck_2eproto();

class TaskCount_Ack;

// ===================================================================

class TaskCount_Ack : public ::google::protobuf::Message {
 public:
  TaskCount_Ack();
  virtual ~TaskCount_Ack();

  TaskCount_Ack(const TaskCount_Ack& from);

  inline TaskCount_Ack& operator=(const TaskCount_Ack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TaskCount_Ack& default_instance();

  void Swap(TaskCount_Ack* other);

  // implements Message ----------------------------------------------

  TaskCount_Ack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TaskCount_Ack& from);
  void MergeFrom(const TaskCount_Ack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string msgInfo = 1;
  inline bool has_msginfo() const;
  inline void clear_msginfo();
  static const int kMsgInfoFieldNumber = 1;
  inline const ::std::string& msginfo() const;
  inline void set_msginfo(const ::std::string& value);
  inline void set_msginfo(const char* value);
  inline void set_msginfo(const char* value, size_t size);
  inline ::std::string* mutable_msginfo();
  inline ::std::string* release_msginfo();
  inline void set_allocated_msginfo(::std::string* msginfo);

  // optional int32 taskcount = 2;
  inline bool has_taskcount() const;
  inline void clear_taskcount();
  static const int kTaskcountFieldNumber = 2;
  inline ::google::protobuf::int32 taskcount() const;
  inline void set_taskcount(::google::protobuf::int32 value);

  // optional int32 mailcount = 3;
  inline bool has_mailcount() const;
  inline void clear_mailcount();
  static const int kMailcountFieldNumber = 3;
  inline ::google::protobuf::int32 mailcount() const;
  inline void set_mailcount(::google::protobuf::int32 value);

  // optional int32 acktime = 4;
  inline bool has_acktime() const;
  inline void clear_acktime();
  static const int kAcktimeFieldNumber = 4;
  inline ::google::protobuf::int32 acktime() const;
  inline void set_acktime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protobuf.TaskCount_Ack)
 private:
  inline void set_has_msginfo();
  inline void clear_has_msginfo();
  inline void set_has_taskcount();
  inline void clear_has_taskcount();
  inline void set_has_mailcount();
  inline void clear_has_mailcount();
  inline void set_has_acktime();
  inline void clear_has_acktime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* msginfo_;
  ::google::protobuf::int32 taskcount_;
  ::google::protobuf::int32 mailcount_;
  ::google::protobuf::int32 acktime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_TaskCount_5fAck_2eproto();
  friend void protobuf_AssignDesc_TaskCount_5fAck_2eproto();
  friend void protobuf_ShutdownFile_TaskCount_5fAck_2eproto();

  void InitAsDefaultInstance();
  static TaskCount_Ack* default_instance_;
};
// ===================================================================


// ===================================================================

// TaskCount_Ack

// optional string msgInfo = 1;
inline bool TaskCount_Ack::has_msginfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TaskCount_Ack::set_has_msginfo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TaskCount_Ack::clear_has_msginfo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TaskCount_Ack::clear_msginfo() {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    msginfo_->clear();
  }
  clear_has_msginfo();
}
inline const ::std::string& TaskCount_Ack::msginfo() const {
  return *msginfo_;
}
inline void TaskCount_Ack::set_msginfo(const ::std::string& value) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(value);
}
inline void TaskCount_Ack::set_msginfo(const char* value) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(value);
}
inline void TaskCount_Ack::set_msginfo(const char* value, size_t size) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskCount_Ack::mutable_msginfo() {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  return msginfo_;
}
inline ::std::string* TaskCount_Ack::release_msginfo() {
  clear_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msginfo_;
    msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskCount_Ack::set_allocated_msginfo(::std::string* msginfo) {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    delete msginfo_;
  }
  if (msginfo) {
    set_has_msginfo();
    msginfo_ = msginfo;
  } else {
    clear_has_msginfo();
    msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 taskcount = 2;
inline bool TaskCount_Ack::has_taskcount() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TaskCount_Ack::set_has_taskcount() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TaskCount_Ack::clear_has_taskcount() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TaskCount_Ack::clear_taskcount() {
  taskcount_ = 0;
  clear_has_taskcount();
}
inline ::google::protobuf::int32 TaskCount_Ack::taskcount() const {
  return taskcount_;
}
inline void TaskCount_Ack::set_taskcount(::google::protobuf::int32 value) {
  set_has_taskcount();
  taskcount_ = value;
}

// optional int32 mailcount = 3;
inline bool TaskCount_Ack::has_mailcount() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TaskCount_Ack::set_has_mailcount() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TaskCount_Ack::clear_has_mailcount() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TaskCount_Ack::clear_mailcount() {
  mailcount_ = 0;
  clear_has_mailcount();
}
inline ::google::protobuf::int32 TaskCount_Ack::mailcount() const {
  return mailcount_;
}
inline void TaskCount_Ack::set_mailcount(::google::protobuf::int32 value) {
  set_has_mailcount();
  mailcount_ = value;
}

// optional int32 acktime = 4;
inline bool TaskCount_Ack::has_acktime() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TaskCount_Ack::set_has_acktime() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TaskCount_Ack::clear_has_acktime() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TaskCount_Ack::clear_acktime() {
  acktime_ = 0;
  clear_has_acktime();
}
inline ::google::protobuf::int32 TaskCount_Ack::acktime() const {
  return acktime_;
}
inline void TaskCount_Ack::set_acktime(::google::protobuf::int32 value) {
  set_has_acktime();
  acktime_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TaskCount_5fAck_2eproto__INCLUDED
