// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpRole_Ack.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "UpRole_Ack.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* UpRole_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UpRole_Ack_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_UpRole_5fAck_2eproto() {
  protobuf_AddDesc_UpRole_5fAck_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "UpRole_Ack.proto");
  GOOGLE_CHECK(file != NULL);
  UpRole_Ack_descriptor_ = file->message_type(0);
  static const int UpRole_Ack_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, msginfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, roletype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, rolelevel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, coin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, diamond_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, breaktype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, ismax_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, acktime_),
  };
  UpRole_Ack_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UpRole_Ack_descriptor_,
      UpRole_Ack::default_instance_,
      UpRole_Ack_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpRole_Ack, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UpRole_Ack));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_UpRole_5fAck_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UpRole_Ack_descriptor_, &UpRole_Ack::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_UpRole_5fAck_2eproto() {
  delete UpRole_Ack::default_instance_;
  delete UpRole_Ack_reflection_;
}

void protobuf_AddDesc_UpRole_5fAck_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020UpRole_Ack.proto\022\010protobuf\"\224\001\n\nUpRole_"
    "Ack\022\017\n\007msgInfo\030\001 \001(\t\022\020\n\010roleType\030\002 \001(\005\022\021"
    "\n\troleLevel\030\003 \001(\005\022\014\n\004coin\030\004 \001(\005\022\017\n\007diamo"
    "nd\030\005 \001(\005\022\021\n\tbreakType\030\006 \001(\010\022\r\n\005isMax\030\007 \001"
    "(\010\022\017\n\007acktime\030\010 \002(\005", 179);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "UpRole_Ack.proto", &protobuf_RegisterTypes);
  UpRole_Ack::default_instance_ = new UpRole_Ack();
  UpRole_Ack::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_UpRole_5fAck_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_UpRole_5fAck_2eproto {
  StaticDescriptorInitializer_UpRole_5fAck_2eproto() {
    protobuf_AddDesc_UpRole_5fAck_2eproto();
  }
} static_descriptor_initializer_UpRole_5fAck_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int UpRole_Ack::kMsgInfoFieldNumber;
const int UpRole_Ack::kRoleTypeFieldNumber;
const int UpRole_Ack::kRoleLevelFieldNumber;
const int UpRole_Ack::kCoinFieldNumber;
const int UpRole_Ack::kDiamondFieldNumber;
const int UpRole_Ack::kBreakTypeFieldNumber;
const int UpRole_Ack::kIsMaxFieldNumber;
const int UpRole_Ack::kAcktimeFieldNumber;
#endif  // !_MSC_VER

UpRole_Ack::UpRole_Ack()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void UpRole_Ack::InitAsDefaultInstance() {
}

UpRole_Ack::UpRole_Ack(const UpRole_Ack& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void UpRole_Ack::SharedCtor() {
  _cached_size_ = 0;
  msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  roletype_ = 0;
  rolelevel_ = 0;
  coin_ = 0;
  diamond_ = 0;
  breaktype_ = false;
  ismax_ = false;
  acktime_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UpRole_Ack::~UpRole_Ack() {
  SharedDtor();
}

void UpRole_Ack::SharedDtor() {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    delete msginfo_;
  }
  if (this != default_instance_) {
  }
}

void UpRole_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UpRole_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UpRole_Ack_descriptor_;
}

const UpRole_Ack& UpRole_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UpRole_5fAck_2eproto();
  return *default_instance_;
}

UpRole_Ack* UpRole_Ack::default_instance_ = NULL;

UpRole_Ack* UpRole_Ack::New() const {
  return new UpRole_Ack;
}

void UpRole_Ack::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_msginfo()) {
      if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
        msginfo_->clear();
      }
    }
    roletype_ = 0;
    rolelevel_ = 0;
    coin_ = 0;
    diamond_ = 0;
    breaktype_ = false;
    ismax_ = false;
    acktime_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UpRole_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string msgInfo = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msginfo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->msginfo().data(), this->msginfo().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_roleType;
        break;
      }

      // optional int32 roleType = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_roleType:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &roletype_)));
          set_has_roletype();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_roleLevel;
        break;
      }

      // optional int32 roleLevel = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_roleLevel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rolelevel_)));
          set_has_rolelevel();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_coin;
        break;
      }

      // optional int32 coin = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_coin:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &coin_)));
          set_has_coin();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_diamond;
        break;
      }

      // optional int32 diamond = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_diamond:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &diamond_)));
          set_has_diamond();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_breakType;
        break;
      }

      // optional bool breakType = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_breakType:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &breaktype_)));
          set_has_breaktype();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_isMax;
        break;
      }

      // optional bool isMax = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isMax:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ismax_)));
          set_has_ismax();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_acktime;
        break;
      }

      // required int32 acktime = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_acktime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &acktime_)));
          set_has_acktime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void UpRole_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string msgInfo = 1;
  if (has_msginfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msginfo().data(), this->msginfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->msginfo(), output);
  }

  // optional int32 roleType = 2;
  if (has_roletype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->roletype(), output);
  }

  // optional int32 roleLevel = 3;
  if (has_rolelevel()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->rolelevel(), output);
  }

  // optional int32 coin = 4;
  if (has_coin()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->coin(), output);
  }

  // optional int32 diamond = 5;
  if (has_diamond()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->diamond(), output);
  }

  // optional bool breakType = 6;
  if (has_breaktype()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->breaktype(), output);
  }

  // optional bool isMax = 7;
  if (has_ismax()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->ismax(), output);
  }

  // required int32 acktime = 8;
  if (has_acktime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->acktime(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UpRole_Ack::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string msgInfo = 1;
  if (has_msginfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msginfo().data(), this->msginfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msginfo(), target);
  }

  // optional int32 roleType = 2;
  if (has_roletype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->roletype(), target);
  }

  // optional int32 roleLevel = 3;
  if (has_rolelevel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->rolelevel(), target);
  }

  // optional int32 coin = 4;
  if (has_coin()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->coin(), target);
  }

  // optional int32 diamond = 5;
  if (has_diamond()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->diamond(), target);
  }

  // optional bool breakType = 6;
  if (has_breaktype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->breaktype(), target);
  }

  // optional bool isMax = 7;
  if (has_ismax()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->ismax(), target);
  }

  // required int32 acktime = 8;
  if (has_acktime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->acktime(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UpRole_Ack::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string msgInfo = 1;
    if (has_msginfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msginfo());
    }

    // optional int32 roleType = 2;
    if (has_roletype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->roletype());
    }

    // optional int32 roleLevel = 3;
    if (has_rolelevel()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->rolelevel());
    }

    // optional int32 coin = 4;
    if (has_coin()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->coin());
    }

    // optional int32 diamond = 5;
    if (has_diamond()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->diamond());
    }

    // optional bool breakType = 6;
    if (has_breaktype()) {
      total_size += 1 + 1;
    }

    // optional bool isMax = 7;
    if (has_ismax()) {
      total_size += 1 + 1;
    }

    // required int32 acktime = 8;
    if (has_acktime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->acktime());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UpRole_Ack::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UpRole_Ack* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UpRole_Ack*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UpRole_Ack::MergeFrom(const UpRole_Ack& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msginfo()) {
      set_msginfo(from.msginfo());
    }
    if (from.has_roletype()) {
      set_roletype(from.roletype());
    }
    if (from.has_rolelevel()) {
      set_rolelevel(from.rolelevel());
    }
    if (from.has_coin()) {
      set_coin(from.coin());
    }
    if (from.has_diamond()) {
      set_diamond(from.diamond());
    }
    if (from.has_breaktype()) {
      set_breaktype(from.breaktype());
    }
    if (from.has_ismax()) {
      set_ismax(from.ismax());
    }
    if (from.has_acktime()) {
      set_acktime(from.acktime());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UpRole_Ack::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpRole_Ack::CopyFrom(const UpRole_Ack& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpRole_Ack::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000080) != 0x00000080) return false;

  return true;
}

void UpRole_Ack::Swap(UpRole_Ack* other) {
  if (other != this) {
    std::swap(msginfo_, other->msginfo_);
    std::swap(roletype_, other->roletype_);
    std::swap(rolelevel_, other->rolelevel_);
    std::swap(coin_, other->coin_);
    std::swap(diamond_, other->diamond_);
    std::swap(breaktype_, other->breaktype_);
    std::swap(ismax_, other->ismax_);
    std::swap(acktime_, other->acktime_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UpRole_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UpRole_Ack_descriptor_;
  metadata.reflection = UpRole_Ack_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)
