// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpRole_Ack.proto

#ifndef PROTOBUF_UpRole_5fAck_2eproto__INCLUDED
#define PROTOBUF_UpRole_5fAck_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UpRole_5fAck_2eproto();
void protobuf_AssignDesc_UpRole_5fAck_2eproto();
void protobuf_ShutdownFile_UpRole_5fAck_2eproto();

class UpRole_Ack;

// ===================================================================

class UpRole_Ack : public ::google::protobuf::Message {
 public:
  UpRole_Ack();
  virtual ~UpRole_Ack();

  UpRole_Ack(const UpRole_Ack& from);

  inline UpRole_Ack& operator=(const UpRole_Ack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpRole_Ack& default_instance();

  void Swap(UpRole_Ack* other);

  // implements Message ----------------------------------------------

  UpRole_Ack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpRole_Ack& from);
  void MergeFrom(const UpRole_Ack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string msgInfo = 1;
  inline bool has_msginfo() const;
  inline void clear_msginfo();
  static const int kMsgInfoFieldNumber = 1;
  inline const ::std::string& msginfo() const;
  inline void set_msginfo(const ::std::string& value);
  inline void set_msginfo(const char* value);
  inline void set_msginfo(const char* value, size_t size);
  inline ::std::string* mutable_msginfo();
  inline ::std::string* release_msginfo();
  inline void set_allocated_msginfo(::std::string* msginfo);

  // optional int32 roleType = 2;
  inline bool has_roletype() const;
  inline void clear_roletype();
  static const int kRoleTypeFieldNumber = 2;
  inline ::google::protobuf::int32 roletype() const;
  inline void set_roletype(::google::protobuf::int32 value);

  // optional int32 roleLevel = 3;
  inline bool has_rolelevel() const;
  inline void clear_rolelevel();
  static const int kRoleLevelFieldNumber = 3;
  inline ::google::protobuf::int32 rolelevel() const;
  inline void set_rolelevel(::google::protobuf::int32 value);

  // optional int32 coin = 4;
  inline bool has_coin() const;
  inline void clear_coin();
  static const int kCoinFieldNumber = 4;
  inline ::google::protobuf::int32 coin() const;
  inline void set_coin(::google::protobuf::int32 value);

  // optional int32 diamond = 5;
  inline bool has_diamond() const;
  inline void clear_diamond();
  static const int kDiamondFieldNumber = 5;
  inline ::google::protobuf::int32 diamond() const;
  inline void set_diamond(::google::protobuf::int32 value);

  // optional bool breakType = 6;
  inline bool has_breaktype() const;
  inline void clear_breaktype();
  static const int kBreakTypeFieldNumber = 6;
  inline bool breaktype() const;
  inline void set_breaktype(bool value);

  // optional bool isMax = 7;
  inline bool has_ismax() const;
  inline void clear_ismax();
  static const int kIsMaxFieldNumber = 7;
  inline bool ismax() const;
  inline void set_ismax(bool value);

  // required int32 acktime = 8;
  inline bool has_acktime() const;
  inline void clear_acktime();
  static const int kAcktimeFieldNumber = 8;
  inline ::google::protobuf::int32 acktime() const;
  inline void set_acktime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protobuf.UpRole_Ack)
 private:
  inline void set_has_msginfo();
  inline void clear_has_msginfo();
  inline void set_has_roletype();
  inline void clear_has_roletype();
  inline void set_has_rolelevel();
  inline void clear_has_rolelevel();
  inline void set_has_coin();
  inline void clear_has_coin();
  inline void set_has_diamond();
  inline void clear_has_diamond();
  inline void set_has_breaktype();
  inline void clear_has_breaktype();
  inline void set_has_ismax();
  inline void clear_has_ismax();
  inline void set_has_acktime();
  inline void clear_has_acktime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* msginfo_;
  ::google::protobuf::int32 roletype_;
  ::google::protobuf::int32 rolelevel_;
  ::google::protobuf::int32 coin_;
  ::google::protobuf::int32 diamond_;
  bool breaktype_;
  bool ismax_;
  ::google::protobuf::int32 acktime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_UpRole_5fAck_2eproto();
  friend void protobuf_AssignDesc_UpRole_5fAck_2eproto();
  friend void protobuf_ShutdownFile_UpRole_5fAck_2eproto();

  void InitAsDefaultInstance();
  static UpRole_Ack* default_instance_;
};
// ===================================================================


// ===================================================================

// UpRole_Ack

// optional string msgInfo = 1;
inline bool UpRole_Ack::has_msginfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpRole_Ack::set_has_msginfo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpRole_Ack::clear_has_msginfo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpRole_Ack::clear_msginfo() {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    msginfo_->clear();
  }
  clear_has_msginfo();
}
inline const ::std::string& UpRole_Ack::msginfo() const {
  return *msginfo_;
}
inline void UpRole_Ack::set_msginfo(const ::std::string& value) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(value);
}
inline void UpRole_Ack::set_msginfo(const char* value) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(value);
}
inline void UpRole_Ack::set_msginfo(const char* value, size_t size) {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  msginfo_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UpRole_Ack::mutable_msginfo() {
  set_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    msginfo_ = new ::std::string;
  }
  return msginfo_;
}
inline ::std::string* UpRole_Ack::release_msginfo() {
  clear_has_msginfo();
  if (msginfo_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msginfo_;
    msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UpRole_Ack::set_allocated_msginfo(::std::string* msginfo) {
  if (msginfo_ != &::google::protobuf::internal::kEmptyString) {
    delete msginfo_;
  }
  if (msginfo) {
    set_has_msginfo();
    msginfo_ = msginfo;
  } else {
    clear_has_msginfo();
    msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 roleType = 2;
inline bool UpRole_Ack::has_roletype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UpRole_Ack::set_has_roletype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UpRole_Ack::clear_has_roletype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UpRole_Ack::clear_roletype() {
  roletype_ = 0;
  clear_has_roletype();
}
inline ::google::protobuf::int32 UpRole_Ack::roletype() const {
  return roletype_;
}
inline void UpRole_Ack::set_roletype(::google::protobuf::int32 value) {
  set_has_roletype();
  roletype_ = value;
}

// optional int32 roleLevel = 3;
inline bool UpRole_Ack::has_rolelevel() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UpRole_Ack::set_has_rolelevel() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UpRole_Ack::clear_has_rolelevel() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UpRole_Ack::clear_rolelevel() {
  rolelevel_ = 0;
  clear_has_rolelevel();
}
inline ::google::protobuf::int32 UpRole_Ack::rolelevel() const {
  return rolelevel_;
}
inline void UpRole_Ack::set_rolelevel(::google::protobuf::int32 value) {
  set_has_rolelevel();
  rolelevel_ = value;
}

// optional int32 coin = 4;
inline bool UpRole_Ack::has_coin() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UpRole_Ack::set_has_coin() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UpRole_Ack::clear_has_coin() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UpRole_Ack::clear_coin() {
  coin_ = 0;
  clear_has_coin();
}
inline ::google::protobuf::int32 UpRole_Ack::coin() const {
  return coin_;
}
inline void UpRole_Ack::set_coin(::google::protobuf::int32 value) {
  set_has_coin();
  coin_ = value;
}

// optional int32 diamond = 5;
inline bool UpRole_Ack::has_diamond() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void UpRole_Ack::set_has_diamond() {
  _has_bits_[0] |= 0x00000010u;
}
inline void UpRole_Ack::clear_has_diamond() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void UpRole_Ack::clear_diamond() {
  diamond_ = 0;
  clear_has_diamond();
}
inline ::google::protobuf::int32 UpRole_Ack::diamond() const {
  return diamond_;
}
inline void UpRole_Ack::set_diamond(::google::protobuf::int32 value) {
  set_has_diamond();
  diamond_ = value;
}

// optional bool breakType = 6;
inline bool UpRole_Ack::has_breaktype() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void UpRole_Ack::set_has_breaktype() {
  _has_bits_[0] |= 0x00000020u;
}
inline void UpRole_Ack::clear_has_breaktype() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void UpRole_Ack::clear_breaktype() {
  breaktype_ = false;
  clear_has_breaktype();
}
inline bool UpRole_Ack::breaktype() const {
  return breaktype_;
}
inline void UpRole_Ack::set_breaktype(bool value) {
  set_has_breaktype();
  breaktype_ = value;
}

// optional bool isMax = 7;
inline bool UpRole_Ack::has_ismax() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void UpRole_Ack::set_has_ismax() {
  _has_bits_[0] |= 0x00000040u;
}
inline void UpRole_Ack::clear_has_ismax() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void UpRole_Ack::clear_ismax() {
  ismax_ = false;
  clear_has_ismax();
}
inline bool UpRole_Ack::ismax() const {
  return ismax_;
}
inline void UpRole_Ack::set_ismax(bool value) {
  set_has_ismax();
  ismax_ = value;
}

// required int32 acktime = 8;
inline bool UpRole_Ack::has_acktime() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void UpRole_Ack::set_has_acktime() {
  _has_bits_[0] |= 0x00000080u;
}
inline void UpRole_Ack::clear_has_acktime() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void UpRole_Ack::clear_acktime() {
  acktime_ = 0;
  clear_has_acktime();
}
inline ::google::protobuf::int32 UpRole_Ack::acktime() const {
  return acktime_;
}
inline void UpRole_Ack::set_acktime(::google::protobuf::int32 value) {
  set_has_acktime();
  acktime_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UpRole_5fAck_2eproto__INCLUDED
