local define_streng_factor = {
	["1"] = {
		["quality"] = 1,
		["streng_expend_factor"] = 3.5,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 4.5,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1.5,
		["agl_add_factor"] = 2,
		["dex_add_factor"] = 3,
		["type"] = 1,

	},
	["2"] = {
		["quality"] = 2,
		["streng_expend_factor"] = 4.275,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 6.5,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2.5,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 2.5,
		["dex_add_factor"] = 3.5,
		["type"] = 1,

	},
	["3"] = {
		["quality"] = 3,
		["streng_expend_factor"] = 5.36,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 9.5,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3,
		["block_add_factor"] = 2.5,
		["agl_add_factor"] = 3,
		["dex_add_factor"] = 4,
		["type"] = 1,

	},
	["4"] = {
		["quality"] = 4,
		["streng_expend_factor"] = 7.2,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 14,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3.5,
		["block_add_factor"] = 3,
		["agl_add_factor"] = 3.5,
		["dex_add_factor"] = 5,
		["type"] = 1,

	},
	["5"] = {
		["quality"] = 5,
		["streng_expend_factor"] = 10,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 23,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 4.5,
		["block_add_factor"] = 3.5,
		["agl_add_factor"] = 4.5,
		["dex_add_factor"] = 6.5,
		["type"] = 1,

	},
	["6"] = {
		["quality"] = 1,
		["streng_expend_factor"] = 2.8,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 3,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1.5,
		["agl_add_factor"] = 2,
		["dex_add_factor"] = 3,
		["type"] = 2,

	},
	["7"] = {
		["quality"] = 2,
		["streng_expend_factor"] = 3.42,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 4,
		["cri_add_factor"] = 2.5,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 2.5,
		["dex_add_factor"] = 3.5,
		["type"] = 2,

	},
	["8"] = {
		["quality"] = 3,
		["streng_expend_factor"] = 4.288,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 6,
		["cri_add_factor"] = 3,
		["block_add_factor"] = 2.5,
		["agl_add_factor"] = 3,
		["dex_add_factor"] = 4,
		["type"] = 2,

	},
	["9"] = {
		["quality"] = 4,
		["streng_expend_factor"] = 5.76,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 9,
		["cri_add_factor"] = 3.5,
		["block_add_factor"] = 3,
		["agl_add_factor"] = 3.5,
		["dex_add_factor"] = 5,
		["type"] = 2,

	},
	["10"] = {
		["quality"] = 5,
		["streng_expend_factor"] = 8,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 15,
		["cri_add_factor"] = 4.5,
		["block_add_factor"] = 3.5,
		["agl_add_factor"] = 4.5,
		["dex_add_factor"] = 6.5,
		["type"] = 2,

	},
	["11"] = {
		["quality"] = 1,
		["streng_expend_factor"] = 4.2,
		["hp_add_factor"] = 15,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1.5,
		["agl_add_factor"] = 2,
		["dex_add_factor"] = 3,
		["type"] = 4,

	},
	["12"] = {
		["quality"] = 2,
		["streng_expend_factor"] = 5.13,
		["hp_add_factor"] = 20.5,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2.5,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 2.5,
		["dex_add_factor"] = 3.5,
		["type"] = 4,

	},
	["13"] = {
		["quality"] = 3,
		["streng_expend_factor"] = 6.432,
		["hp_add_factor"] = 30,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3,
		["block_add_factor"] = 2.5,
		["agl_add_factor"] = 3,
		["dex_add_factor"] = 4,
		["type"] = 4,

	},
	["14"] = {
		["quality"] = 4,
		["streng_expend_factor"] = 8.64,
		["hp_add_factor"] = 44.5,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3.5,
		["block_add_factor"] = 3,
		["agl_add_factor"] = 3.5,
		["dex_add_factor"] = 5,
		["type"] = 4,

	},
	["15"] = {
		["quality"] = 5,
		["streng_expend_factor"] = 12,
		["hp_add_factor"] = 72.5,
		["def_add_factor"] = 0,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 4.5,
		["block_add_factor"] = 3.5,
		["agl_add_factor"] = 4.5,
		["dex_add_factor"] = 6.5,
		["type"] = 4,

	},
	["16"] = {
		["quality"] = 1,
		["streng_expend_factor"] = 2.1,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 1,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2,
		["block_add_factor"] = 1.5,
		["agl_add_factor"] = 2,
		["dex_add_factor"] = 3,
		["type"] = 5,

	},
	["17"] = {
		["quality"] = 2,
		["streng_expend_factor"] = 2.565,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 1.5,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 2.5,
		["block_add_factor"] = 2,
		["agl_add_factor"] = 2.5,
		["dex_add_factor"] = 3.5,
		["type"] = 5,

	},
	["18"] = {
		["quality"] = 3,
		["streng_expend_factor"] = 3.216,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 2,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3,
		["block_add_factor"] = 2.5,
		["agl_add_factor"] = 3,
		["dex_add_factor"] = 4,
		["type"] = 5,

	},
	["19"] = {
		["quality"] = 4,
		["streng_expend_factor"] = 4.32,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 3,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 3.5,
		["block_add_factor"] = 3,
		["agl_add_factor"] = 3.5,
		["dex_add_factor"] = 5,
		["type"] = 5,

	},
	["20"] = {
		["quality"] = 5,
		["streng_expend_factor"] = 6,
		["hp_add_factor"] = 0,
		["def_add_factor"] = 5.5,
		["atk_add_factor"] = 0,
		["zhili_add_factor"] = 0,
		["cri_add_factor"] = 4.5,
		["block_add_factor"] = 3.5,
		["agl_add_factor"] = 4.5,
		["dex_add_factor"] = 6.5,
		["type"] = 5,

	},

}
return define_streng_factor
