local define_task = {
	["1"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到1天",
		["pre_task_id"] = 0,
		["condition1"] = 1,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "73:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["2"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到2天",
		["pre_task_id"] = 1,
		["condition1"] = 2,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3024:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["3"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到3天",
		["pre_task_id"] = 2,
		["condition1"] = 3,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "1001:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["4"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到4天",
		["pre_task_id"] = 3,
		["condition1"] = 4,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "73:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["5"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到5天",
		["pre_task_id"] = 4,
		["condition1"] = 5,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "5101:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["6"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到6天",
		["pre_task_id"] = 5,
		["condition1"] = 6,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "73:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["7"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到7天",
		["pre_task_id"] = 6,
		["condition1"] = 7,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "6000:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["8"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到8天",
		["pre_task_id"] = 7,
		["condition1"] = 8,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "1001:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["9"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到9天",
		["pre_task_id"] = 8,
		["condition1"] = 9,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3024:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["10"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到10天",
		["pre_task_id"] = 9,
		["condition1"] = 10,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:30",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["11"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到11天",
		["pre_task_id"] = 10,
		["condition1"] = 11,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "5102:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["12"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到12天",
		["pre_task_id"] = 11,
		["condition1"] = 12,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "73:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["13"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到13天",
		["pre_task_id"] = 12,
		["condition1"] = 13,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "6001:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["14"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到14天",
		["pre_task_id"] = 13,
		["condition1"] = 14,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:30",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["15"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到15天",
		["pre_task_id"] = 14,
		["condition1"] = 15,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "1:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["16"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到16天",
		["pre_task_id"] = 15,
		["condition1"] = 16,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3024:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["17"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到17天",
		["pre_task_id"] = 16,
		["condition1"] = 17,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:30",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["18"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到18天",
		["pre_task_id"] = 17,
		["condition1"] = 18,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "2:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["19"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到19天",
		["pre_task_id"] = 18,
		["condition1"] = 19,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "5103:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["20"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到20天",
		["pre_task_id"] = 19,
		["condition1"] = 20,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "6002:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["21"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到21天",
		["pre_task_id"] = 20,
		["condition1"] = 21,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:30",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["22"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到22天",
		["pre_task_id"] = 21,
		["condition1"] = 22,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["23"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到23天",
		["pre_task_id"] = 22,
		["condition1"] = 23,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "5104:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["24"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到24天",
		["pre_task_id"] = 23,
		["condition1"] = 24,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "73:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["25"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到25天",
		["pre_task_id"] = 24,
		["condition1"] = 25,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:30",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["26"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到26天",
		["pre_task_id"] = 25,
		["condition1"] = 26,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3024:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["27"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到27天",
		["pre_task_id"] = 26,
		["condition1"] = 27,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "4:1",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["28"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到28天",
		["pre_task_id"] = 27,
		["condition1"] = 28,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "5105:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["29"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到29天",
		["pre_task_id"] = 28,
		["condition1"] = 29,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:30",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["30"] = {
		["name"] = "签到任务",
		["type"] = 1,
		["task_desc"] = "签到30天",
		["pre_task_id"] = 29,
		["condition1"] = 30,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3024:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["31"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计1天",
		["pre_task_id"] = 0,
		["condition1"] = 1,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3011:30",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["32"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计2天",
		["pre_task_id"] = 31,
		["condition1"] = 2,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3011:30",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["33"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计3天",
		["pre_task_id"] = 32,
		["condition1"] = 3,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3011:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["34"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计4天",
		["pre_task_id"] = 33,
		["condition1"] = 4,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3011:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["35"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计5天",
		["pre_task_id"] = 34,
		["condition1"] = 5,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3011:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["36"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计6天",
		["pre_task_id"] = 35,
		["condition1"] = 6,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3011:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["37"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计7天",
		["pre_task_id"] = 36,
		["condition1"] = 7,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3011:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["38"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计8天",
		["pre_task_id"] = 37,
		["condition1"] = 8,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["39"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计9天",
		["pre_task_id"] = 38,
		["condition1"] = 9,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["40"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计10天",
		["pre_task_id"] = 39,
		["condition1"] = 10,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["41"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计11天",
		["pre_task_id"] = 40,
		["condition1"] = 11,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["42"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计12天",
		["pre_task_id"] = 41,
		["condition1"] = 12,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["43"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计13天",
		["pre_task_id"] = 42,
		["condition1"] = 13,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["44"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计14天",
		["pre_task_id"] = 43,
		["condition1"] = 14,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["45"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计15天",
		["pre_task_id"] = 44,
		["condition1"] = 15,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["46"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计16天",
		["pre_task_id"] = 45,
		["condition1"] = 16,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["47"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计17天",
		["pre_task_id"] = 46,
		["condition1"] = 17,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["48"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计18天",
		["pre_task_id"] = 47,
		["condition1"] = 18,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["49"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计19天",
		["pre_task_id"] = 48,
		["condition1"] = 19,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["50"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计20天",
		["pre_task_id"] = 49,
		["condition1"] = 20,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["51"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计21天",
		["pre_task_id"] = 50,
		["condition1"] = 21,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["52"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计22天",
		["pre_task_id"] = 51,
		["condition1"] = 22,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["53"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计23天",
		["pre_task_id"] = 52,
		["condition1"] = 23,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["54"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计24天",
		["pre_task_id"] = 53,
		["condition1"] = 24,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["55"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计25天",
		["pre_task_id"] = 54,
		["condition1"] = 25,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["56"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计26天",
		["pre_task_id"] = 55,
		["condition1"] = 26,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["57"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计27天",
		["pre_task_id"] = 56,
		["condition1"] = 27,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["58"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计28天",
		["pre_task_id"] = 57,
		["condition1"] = 28,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["59"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计29天",
		["pre_task_id"] = 58,
		["condition1"] = 29,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["60"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计30天",
		["pre_task_id"] = 59,
		["condition1"] = 30,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["61"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计31天",
		["pre_task_id"] = 60,
		["condition1"] = 31,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["62"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计32天",
		["pre_task_id"] = 61,
		["condition1"] = 32,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["63"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计33天",
		["pre_task_id"] = 62,
		["condition1"] = 33,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["64"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计34天",
		["pre_task_id"] = 63,
		["condition1"] = 34,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["65"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计35天",
		["pre_task_id"] = 64,
		["condition1"] = 35,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["66"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计36天",
		["pre_task_id"] = 65,
		["condition1"] = 36,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["67"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计37天",
		["pre_task_id"] = 66,
		["condition1"] = 37,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["68"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计38天",
		["pre_task_id"] = 67,
		["condition1"] = 38,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["69"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计39天",
		["pre_task_id"] = 68,
		["condition1"] = 39,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["70"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计40天",
		["pre_task_id"] = 69,
		["condition1"] = 40,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["71"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计41天",
		["pre_task_id"] = 70,
		["condition1"] = 41,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["72"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计42天",
		["pre_task_id"] = 71,
		["condition1"] = 42,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["73"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计43天",
		["pre_task_id"] = 72,
		["condition1"] = 43,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["74"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计44天",
		["pre_task_id"] = 73,
		["condition1"] = 44,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["75"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计45天",
		["pre_task_id"] = 74,
		["condition1"] = 45,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["76"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计46天",
		["pre_task_id"] = 75,
		["condition1"] = 46,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["77"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计47天",
		["pre_task_id"] = 76,
		["condition1"] = 47,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["78"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计48天",
		["pre_task_id"] = 77,
		["condition1"] = 48,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["79"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计49天",
		["pre_task_id"] = 78,
		["condition1"] = 49,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["80"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计50天",
		["pre_task_id"] = 79,
		["condition1"] = 50,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["81"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计51天",
		["pre_task_id"] = 80,
		["condition1"] = 51,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["82"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计52天",
		["pre_task_id"] = 81,
		["condition1"] = 52,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["83"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计53天",
		["pre_task_id"] = 82,
		["condition1"] = 53,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["84"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计54天",
		["pre_task_id"] = 83,
		["condition1"] = 54,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["85"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计55天",
		["pre_task_id"] = 84,
		["condition1"] = 55,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["86"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计56天",
		["pre_task_id"] = 85,
		["condition1"] = 56,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["87"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计57天",
		["pre_task_id"] = 86,
		["condition1"] = 57,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["88"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计58天",
		["pre_task_id"] = 87,
		["condition1"] = 58,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["89"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计59天",
		["pre_task_id"] = 88,
		["condition1"] = 59,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["90"] = {
		["name"] = "累计登陆任务",
		["type"] = 2,
		["task_desc"] = "累计60天",
		["pre_task_id"] = 89,
		["condition1"] = 60,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["91"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = 主角5级,
		["pre_task_id"] = 0,
		["condition1"] = 5,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["92"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角10级",
		["pre_task_id"] = 91,
		["condition1"] = 10,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:20",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["93"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角15级",
		["pre_task_id"] = 92,
		["condition1"] = 15,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:15",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["94"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角20级",
		["pre_task_id"] = 93,
		["condition1"] = 20,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:15",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["95"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角25级",
		["pre_task_id"] = 94,
		["condition1"] = 25,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:15",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["96"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角30级",
		["pre_task_id"] = 95,
		["condition1"] = 30,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:15",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["97"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角35级",
		["pre_task_id"] = 96,
		["condition1"] = 35,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:15",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["98"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角40级",
		["pre_task_id"] = 97,
		["condition1"] = 40,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:15",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["99"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角45级",
		["pre_task_id"] = 98,
		["condition1"] = 45,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:15",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["100"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角50级",
		["pre_task_id"] = 99,
		["condition1"] = 50,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "3007:15",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["101"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角55级",
		["pre_task_id"] = 100,
		["condition1"] = 55,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["102"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角60级",
		["pre_task_id"] = 101,
		["condition1"] = 60,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["103"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角65级",
		["pre_task_id"] = 102,
		["condition1"] = 65,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["104"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角70级",
		["pre_task_id"] = 103,
		["condition1"] = 70,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["105"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角75级",
		["pre_task_id"] = 104,
		["condition1"] = 75,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["106"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角80级",
		["pre_task_id"] = 105,
		["condition1"] = 80,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["107"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角85级",
		["pre_task_id"] = 106,
		["condition1"] = 85,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["108"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角90级",
		["pre_task_id"] = 107,
		["condition1"] = 90,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["109"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角95级",
		["pre_task_id"] = 108,
		["condition1"] = 95,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["110"] = {
		["name"] = "成长任务",
		["type"] = 3,
		["task_desc"] = "主角100级",
		["pre_task_id"] = 109,
		["condition1"] = 100,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "9000:10",
		["gold"] = 0,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["111"] = {
		["name"] = "剧情任务",
		["type"] = 4,
		["task_desc"] = "通关丹莫罗",
		["pre_task_id"] = 0,
		["condition1"] = 13,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 50,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["112"] = {
		["name"] = "剧情任务",
		["type"] = 4,
		["task_desc"] = "通关莫高雷",
		["pre_task_id"] = 111,
		["condition1"] = 26,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 100,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["113"] = {
		["name"] = "剧情任务",
		["type"] = 4,
		["task_desc"] = "通关赤脊山",
		["pre_task_id"] = 112,
		["condition1"] = 39,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 150,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["114"] = {
		["name"] = "剧情任务",
		["type"] = 4,
		["task_desc"] = "通关贫瘠之地",
		["pre_task_id"] = 113,
		["condition1"] = 52,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 200,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["115"] = {
		["name"] = "剧情任务",
		["type"] = 4,
		["task_desc"] = "通关丘陵",
		["pre_task_id"] = 114,
		["condition1"] = 65,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 250,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["116"] = {
		["name"] = "剧情任务",
		["type"] = 4,
		["task_desc"] = "通关湿地",
		["pre_task_id"] = 115,
		["condition1"] = 78,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 300,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["117"] = {
		["name"] = "剧情任务",
		["type"] = 4,
		["task_desc"] = "通关灰谷森林",
		["pre_task_id"] = 116,
		["condition1"] = 91,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 350,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["118"] = {
		["name"] = "剧情任务",
		["type"] = 5,
		["task_desc"] = "通关精英丹莫罗",
		["pre_task_id"] = 0,
		["condition1"] = 104,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 100,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["119"] = {
		["name"] = "剧情任务",
		["type"] = 5,
		["task_desc"] = "通关精英莫高雷",
		["pre_task_id"] = 118,
		["condition1"] = 117,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 200,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["120"] = {
		["name"] = "剧情任务",
		["type"] = 5,
		["task_desc"] = "通关精英赤脊山",
		["pre_task_id"] = 119,
		["condition1"] = 130,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 300,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["121"] = {
		["name"] = "剧情任务",
		["type"] = 5,
		["task_desc"] = "通关精英贫瘠之地",
		["pre_task_id"] = 120,
		["condition1"] = 143,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 400,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["122"] = {
		["name"] = "剧情任务",
		["type"] = 5,
		["task_desc"] = "通关精英丘陵",
		["pre_task_id"] = 121,
		["condition1"] = 156,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 500,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["123"] = {
		["name"] = "剧情任务",
		["type"] = 5,
		["task_desc"] = "通关精英湿地",
		["pre_task_id"] = 122,
		["condition1"] = 169,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 600,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["124"] = {
		["name"] = "剧情任务",
		["type"] = 5,
		["task_desc"] = "通关精英灰谷森林",
		["pre_task_id"] = 123,
		["condition1"] = 182,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 700,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["125"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集6个英雄",
		["pre_task_id"] = 0,
		["condition1"] = 6,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 5,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["126"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集8个英雄",
		["pre_task_id"] = 125,
		["condition1"] = 8,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 10,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["127"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集10个英雄",
		["pre_task_id"] = 126,
		["condition1"] = 10,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 15,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["128"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集12个英雄",
		["pre_task_id"] = 127,
		["condition1"] = 12,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 20,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["129"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集14个英雄",
		["pre_task_id"] = 128,
		["condition1"] = 14,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 25,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["130"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集16个英雄",
		["pre_task_id"] = 129,
		["condition1"] = 16,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 30,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["131"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集18个英雄",
		["pre_task_id"] = 130,
		["condition1"] = 18,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 35,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["132"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集20个英雄",
		["pre_task_id"] = 131,
		["condition1"] = 20,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 40,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["133"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集22个英雄",
		["pre_task_id"] = 132,
		["condition1"] = 22,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 45,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["134"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集24个英雄",
		["pre_task_id"] = 133,
		["condition1"] = 24,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 50,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["135"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集26个英雄",
		["pre_task_id"] = 134,
		["condition1"] = 26,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 55,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["136"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集28个英雄",
		["pre_task_id"] = 135,
		["condition1"] = 28,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 60,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},
	["137"] = {
		["name"] = "收集英雄",
		["type"] = 6,
		["task_desc"] = "收集30个英雄",
		["pre_task_id"] = 136,
		["condition1"] = 30,
		["condition2"] = 0,
		["condition3"] = 0,
		["item"] = "0",
		["gold"] = 65,
		["coins"] = 0,
		["exp"] = 0,
		["soul_id"] = 0,
		["icon"] = "9",

	},

}
return define_task
