local define_daily_task = {
	["1"] = {
		["type"] = "0",
		["num"] = "20",
		["name"] = "闯关",
		["desc"] = "参加PVE关卡20次",
		["atonce_cost"] = "50",
		["gold"] = "5",
		["coins"] = "3000",
		["energy"] = "0",
		["roll_count"] = "1",
		["item"] = "3027,2",
		["icon"] = "daily_task_1",
		["exp"] = "0",
		["start_tm"] ="" ,
		["end_tm"] = "",
		["level"] = "1",

	},
	["2"] = {
		["type"] = "3",
		["num"] = "1",
		["name"] = "抽英雄",
		["desc"] = "抽英雄1次",
		["atonce_cost"] = "50",
		["gold"] = "10",
		["coins"] = "5000",
		["energy"] = "0",
		["roll_count"] = "1",
		["item"] = "3027,2",
		["icon"] = "daily_task_5",
		["exp"] = "0",
		["start_tm"] ="" ,
		["end_tm"] = "",
		["level"] = "1",

	},
	["3"] = {
		["type"] = "4",
		["num"] = "1",
		["name"] = "黄金宝箱",
		["desc"] = "开黄金宝箱1个",
		["atonce_cost"] = "50",
		["gold"] = "10",
		["coins"] = "5000",
		["energy"] = "0",
		["roll_count"] = "1",
		["item"] = "3027,1",
		["icon"] = "daily_task_2",
		["exp"] = "0",
		["start_tm"] ="" ,
		["end_tm"] = "",
		["level"] = "1",

	},
	["4"] = {
		["type"] = "5",
		["num"] = "10",
		["name"] = "夺宝",
		["desc"] = "参加夺宝战10次",
		["atonce_cost"] = "50",
		["gold"] = "5",
		["coins"] = "4000",
		["energy"] = "0",
		["roll_count"] = "1",
		["item"] = "3027,2",
		["icon"] = "daily_task_3",
		["exp"] = "0",
		["start_tm"] ="" ,
		["end_tm"] = "",
		["level"] = "5",

	},
	["5"] = {
		["type"] = "6",
		["num"] = "5",
		["name"] = "竞技场",
		["desc"] = "在竞技场里战斗5次",
		["atonce_cost"] = "50",
		["gold"] = "5",
		["coins"] = "3000",
		["energy"] = "0",
		["roll_count"] = "1",
		["item"] = "3027,2",
		["icon"] = "daily_task_4",
		["exp"] = "0",
		["start_tm"] ="" ,
		["end_tm"] = "",
		["level"] = "18",

	},
	["6"] = {
		["type"] = "9",
		["num"] = "0",
		["name"] = "豪华午餐",
		["desc"] = "每日12:00至14:00可领50点体力",
		["atonce_cost"] = "0",
		["gold"] = "0",
		["coins"] = "0",
		["energy"] = "50",
		["roll_count"] = "0",
		["item"] = "",
		["icon"] = "daily_task_7",
		["exp"] = "0",
		["start_tm"] = "12:00:00",
		["end_tm"] = "14:00:00",
		["level"] = "0",

	},
	["7"] = {
		["type"] = "9",
		["num"] = "0",
		["name"] = "豪华晚餐",
		["desc"] = "每日18:00至20:00可领50点体力",
		["atonce_cost"] = "0",
		["gold"] = "0",
		["coins"] = "0",
		["energy"] = "50",
		["roll_count"] = "0",
		["item"] = "",
		["icon"] = "daily_task_8",
		["exp"] = "0",
		["start_tm"] = "18:00:00",
		["end_tm"] = "20:00:00",
		["level"] = "0",

	},
	["8"] = {
		["type"] = "10",
		["num"] = "1",
		["name"] = "月卡",
		["desc"] = "买月卡送东西",
		["atonce_cost"] = "0",
		["gold"] = "20",
		["coins"] = "0",
		["energy"] = "0",
		["roll_count"] = "0",
		["item"] = "3027,2",
		["icon"] = "daily_task_6",
		["exp"] = "0",
		["start_tm"] ="" ,
		["end_tm"] = "",
		["level"] = "0",

	},

}
return define_daily_task
