local juexing_skill = {
	["1"] = {
		["name"] = "雷神之锤",
		["icon"] = 5000,
		["dic"] = "己方全体英雄，在一定时间内免疫眩晕效果。当前眩晕状态的恢复正常",
		["cd"] = 13,
		["lv_num"] = 2,
		["hero_id"] = "3;16",
		["dt"] = 20000,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["2"] = {
		["name"] = "火炮轰炸",
		["icon"] = 5001,
		["dic"] = "对全体敌方单位，给予持续伤害",
		["cd"] = 25,
		["lv_num"] = 2,
		["hero_id"] = "5;18",
		["dt"] = 0,
		["hp_factor"] = 1,
		["slice_num"] = 5,
		["slice_dt"] = 400,
		["slice_hp_factor"] = 1,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["3"] = {
		["name"] = "召唤箭塔车",
		["icon"] = 5002,
		["dic"] = "射击最近的敌方个体，优先攻击车辆建筑",
		["cd"] = 10,
		["lv_num"] = 2,
		["hero_id"] = "9;19",
		["dt"] = 0,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["4"] = {
		["name"] = "召唤魔法塔",
		["icon"] = 5003,
		["dic"] = "重创最近的敌方个体，优先攻击车辆建筑",
		["cd"] = 20,
		["lv_num"] = 2,
		["hero_id"] = "22;28",
		["dt"] = 0,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 5,

	},
	["5"] = {
		["name"] = "召唤烟雾",
		["icon"] = 5004,
		["dic"] = "生成烟雾，降低敌方的命中率",
		["cd"] = 14,
		["lv_num"] = 2,
		["hero_id"] = "2;24",
		["dt"] = 30000,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0.4,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["6"] = {
		["name"] = "绘制召唤阵",
		["icon"] = 5006,
		["dic"] = "绘制出法阵，从里面不断出现增援的喽啰",
		["cd"] = 17,
		["lv_num"] = 2,
		["hero_id"] = "1;7",
		["dt"] = 0,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["7"] = {
		["name"] = "卫星定位",
		["icon"] = 5007,
		["dic"] = "增加己方全体成员的命中率",
		["cd"] = 14,
		["lv_num"] = 2,
		["hero_id"] = "8;13",
		["dt"] = 30000,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 1,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["8"] = {
		["name"] = "图腾柱",
		["icon"] = 5008,
		["dic"] = "己方全体成员，攻击力防御力都增强一段时间",
		["cd"] = 20,
		["lv_num"] = 2,
		["hero_id"] = "12;14",
		["dt"] = 15000,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 1.2,
		["add_def_factor"] = 1.3,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["9"] = {
		["name"] = "大回血",
		["icon"] = 5009,
		["dic"] = "己方全体英雄，恢复一定的血量",
		["cd"] = 25,
		["lv_num"] = 2,
		["hero_id"] = "10;20",
		["dt"] = 0,
		["hp_factor"] = 2,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["10"] = {
		["name"] = "解毒",
		["icon"] = 5010,
		["dic"] = "为己方的中毒英雄解毒",
		["cd"] = 16,
		["lv_num"] = 2,
		["hero_id"] = "26;27",
		["dt"] = 0,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["11"] = {
		["name"] = "虚弱",
		["icon"] = 5011,
		["dic"] = "敌方全体英雄、小兵，攻击力防御力都降低一段时间",
		["cd"] = 20,
		["lv_num"] = 2,
		["hero_id"] = "4;30",
		["dt"] = 10000,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["12"] = {
		["name"] = "圣光",
		["icon"] = 5012,
		["dic"] = "处于眩晕、虚弱、中毒状态的成员，解除其效果",
		["cd"] = 20,
		["lv_num"] = 2,
		["hero_id"] = "6;23",
		["dt"] = 0,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["13"] = {
		["name"] = "暴风雪",
		["icon"] = 5013,
		["dic"] = "伤害并眩晕全体敌方单位，优先攻击各种车辆",
		["cd"] = 18,
		["lv_num"] = 2,
		["hero_id"] = "17;21",
		["dt"] = 10000,
		["hp_factor"] = 0.3,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["14"] = {
		["name"] = "火雨",
		["icon"] = 5014,
		["dic"] = "伤害敌方全体英雄、小兵",
		["cd"] = 22,
		["lv_num"] = 2,
		["hero_id"] = "15;25",
		["dt"] = 0,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},
	["15"] = {
		["name"] = "闪电",
		["icon"] = 5015,
		["dic"] = "眩晕最近的敌方单位，优先攻击各种车辆",
		["cd"] = 18,
		["lv_num"] = 2,
		["hero_id"] = "11;29",
		["dt"] = 0,
		["hp_factor"] = 1,
		["slice_num"] = 0,
		["slice_dt"] = 0,
		["slice_hp_factor"] = 0,
		["add_atk_factor"] = 0,
		["add_def_factor"] = 0,
		["add_iq_factor"] = 0,
		["add_hit_factor"] = 0,
		["add_gedang_factor"] = 0,
		["add_miss_factor"] = 0,
		["add_baoji_factor"] = 0,
		["recruit_num"] = 0,

	},

}
return juexing_skill
