local define_daily_task = {
	["1"] = {
		["type"] = 0,
		["num"] = 10,
		["name"] = "闯关",
		["desc"] = "参加PVE关卡10次",
		["atonce_cost"] = 50,
		["gold"] = 5,
		["coins"] = 200,
		["energy"] = 0,
		["roll_count"] = 1,
		["item"] = "",
		["icon"] = "1",
		["exp"] = 1,
		["start_tm"] = "",
		["end_tm"] = "",
		["level"] = 1,

	},
	["2"] = {
		["type"] = 3,
		["num"] = 5,
		["name"] = "抽英雄",
		["desc"] = "用金币抽英雄5次",
		["atonce_cost"] = 50,
		["gold"] = 5,
		["coins"] = 500,
		["energy"] = 0,
		["roll_count"] = 1,
		["item"] = "",
		["icon"] = "4",
		["exp"] = 0,
		["start_tm"] = "",
		["end_tm"] = "",
		["level"] = 5,

	},
	["3"] = {
		["type"] = 4,
		["num"] = 1,
		["name"] = "黄金宝箱",
		["desc"] = "开黄金宝箱1个",
		["atonce_cost"] = 50,
		["gold"] = 5,
		["coins"] = 200,
		["energy"] = 0,
		["roll_count"] = 1,
		["item"] = "",
		["icon"] = "5",
		["exp"] = 0,
		["start_tm"] = "",
		["end_tm"] = "",
		["level"] = 5,

	},
	["4"] = {
		["type"] = 5,
		["num"] = 3,
		["name"] = "夺宝",
		["desc"] = "参加夺宝战3次",
		["atonce_cost"] = 50,
		["gold"] = 2,
		["coins"] = 200,
		["energy"] = 0,
		["roll_count"] = 1,
		["item"] = "",
		["icon"] = "6",
		["exp"] = 1,
		["start_tm"] = "",
		["end_tm"] = "",
		["level"] = 12,

	},
	["5"] = {
		["type"] = 6,
		["num"] = 5,
		["name"] = "竞技场",
		["desc"] = "在竞技场里战斗5次",
		["atonce_cost"] = 50,
		["gold"] = 5,
		["coins"] = 200,
		["energy"] = 0,
		["roll_count"] = 1,
		["item"] = "",
		["icon"] = "7",
		["exp"] = 1,
		["start_tm"] = "",
		["end_tm"] = "",
		["level"] = 18,

	},
	["6"] = {
		["type"] = 9,
		["num"] = 0,
		["name"] = "豪华午餐",
		["desc"] = "每日12:00至14:00可领25点体力",
		["atonce_cost"] = 0,
		["gold"] = 0,
		["coins"] = 0,
		["energy"] = 25,
		["roll_count"] = 0,
		["item"] = "",
		["icon"] = "5",
		["exp"] = 0,
		["start_tm"] = "12:00:00",
		["end_tm"] = "14:00:00",
		["level"] = 0,

	},
	["7"] = {
		["type"] = 9,
		["num"] = 0,
		["name"] = "豪华晚餐",
		["desc"] = "每日18:00至20:00可领25点体力",
		["atonce_cost"] = 0,
		["gold"] = 0,
		["coins"] = 0,
		["energy"] = 25,
		["roll_count"] = 0,
		["item"] = "",
		["icon"] = "6",
		["exp"] = 0,
		["start_tm"] = "18:00:00",
		["end_tm"] = "20:00:00",
		["level"] = 0,

	},
	["8"] = {
		["type"] = 10,
		["num"] = 1,
		["name"] = "月卡",
		["desc"] = "买月卡送东西",
		["atonce_cost"] = 0,
		["gold"] = 20,
		["coins"] = 0,
		["energy"] = 0,
		["roll_count"] = 0,
		["item"] = "",
		["icon"] = "7",
		["exp"] = 0,
		["start_tm"] = "",
		["end_tm"] = "",
		["level"] = 0,

	},

}
return define_daily_task
