local define_starsoul_call = {
	["1"] = {
		["be_called"] = "0",
		["name"] = "沃金",
		["hunt_cost"] = "8000",
		["call_cost"] = "0",
		["tonext_rate"] = "50",
		["white_rate"] = "60",
		["green_rate"] = "40",
		["blue_rate"] = "0",
		["purple_rate"] = "0",
		["red_rate"] = "0",
		["exp_rate"] = "0",
		["frag_rate"] = "0",

	},
	["2"] = {
		["be_called"] = "0",
		["name"] = "凯恩血蹄",
		["hunt_cost"] = "10000",
		["call_cost"] = "0",
		["tonext_rate"] = "20",
		["white_rate"] = "50",
		["green_rate"] = "40",
		["blue_rate"] = "40",
		["purple_rate"] = "0",
		["red_rate"] = "0",
		["exp_rate"] = "0",
		["frag_rate"] = "0",

	},
	["3"] = {
		["be_called"] = "0",
		["name"] = "泰兰德语风",
		["hunt_cost"] = "20000",
		["call_cost"] = "0",
		["tonext_rate"] = "30",
		["white_rate"] = "40",
		["green_rate"] = "40",
		["blue_rate"] = "15",
		["purple_rate"] = "5",
		["red_rate"] = "0",
		["exp_rate"] = "0",
		["frag_rate"] = "0",

	},
	["4"] = {
		["be_called"] = "1",
		["name"] = "伊利丹",
		["hunt_cost"] = "40000",
		["call_cost"] = "100",
		["tonext_rate"] = "30",
		["white_rate"] = "0",
		["green_rate"] = "55",
		["blue_rate"] = "20",
		["purple_rate"] = "12",
		["red_rate"] = "8",
		["exp_rate"] = "5",
		["frag_rate"] = "5",

	},
	["5"] = {
		["be_called"] = "0",
		["name"] = "阿尔萨斯",
		["hunt_cost"] = "60000",
		["call_cost"] = "0",
		["tonext_rate"] = "0",
		["white_rate"] = "0",
		["green_rate"] = "40",
		["blue_rate"] = "25",
		["purple_rate"] = "15",
		["red_rate"] = "10",
		["exp_rate"] = "5",
		["frag_rate"] = "5",

	},

}
return define_starsoul_call
