local define_skill = {
	["1"] = {
		["buff_id"] = "1",
		["skill_icon"] = "soul_pic_soulicon001",
		["skill_name"] = "skill_name_1",
		["skill_tips"] = "skill_tips_1",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_hammer",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_blueice",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_lightingblue",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "10",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["2"] = {
		["buff_id"] = "2",
		["skill_icon"] = "soul_pic_soulicon002",
		["skill_name"] = "skill_name_2",
		["skill_tips"] = "skill_tips_2",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_phoenix",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_fire",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_pillar",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["3"] = {
		["buff_id"] = "3",
		["skill_icon"] = "soul_pic_soulicon003",
		["skill_name"] = "skill_name_3",
		["skill_tips"] = "skill_tips_3",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_knife",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_blueice",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_water",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["4"] = {
		["buff_id"] = "4",
		["skill_icon"] = "soul_pic_soulicon004",
		["skill_name"] = "skill_name_4",
		["skill_tips"] = "skill_tips_4",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_axe",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_red",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_axe",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["5"] = {
		["buff_id"] = "5",
		["skill_icon"] = "soul_pic_soulicon005",
		["skill_name"] = "skill_name_5",
		["skill_tips"] = "skill_tips_5",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_axe",
		["scatter_num"] = "3",
		["track_bullets_num"] = "6",
		["trajectory_name"] = "fight_pic_path_blacksmoke",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_fire",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["6"] = {
		["buff_id"] = "6",
		["skill_icon"] = "soul_pic_soulicon006",
		["skill_name"] = "skill_name_6",
		["skill_tips"] = "skill_tips_6",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_arrow",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_blueice",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_bomb",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["7"] = {
		["buff_id"] = "7",
		["skill_icon"] = "soul_pic_soulicon007",
		["skill_name"] = "skill_name_7",
		["skill_tips"] = "skill_tips_7",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_purple",
		["scatter_num"] = "5",
		["track_bullets_num"] = "10",
		["trajectory_name"] = "fight_pic_path_purplespot",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_lightingpure",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["8"] = {
		["buff_id"] = "8",
		["skill_icon"] = "soul_pic_soulicon008",
		["skill_name"] = "skill_name_8",
		["skill_tips"] = "skill_tips_8",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_axe",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_red",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_bomb",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["9"] = {
		["buff_id"] = "9",
		["skill_icon"] = "soul_pic_soulicon009",
		["skill_name"] = "skill_name_9",
		["skill_tips"] = "skill_tips_9",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_fire",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_blacksmoke",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_fire",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["10"] = {
		["buff_id"] = "10",
		["skill_icon"] = "soul_pic_soulicon010",
		["skill_name"] = "skill_name_10",
		["skill_tips"] = "skill_tips_10",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_arrow",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_white",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_bomb",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["11"] = {
		["buff_id"] = "11",
		["skill_icon"] = "soul_pic_soulicon011",
		["skill_name"] = "skill_name_11",
		["skill_tips"] = "skill_tips_11",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_firestone",
		["scatter_num"] = "2",
		["track_bullets_num"] = "5",
		["trajectory_name"] = "fight_pic_path_blacksmoke",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_fire",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["12"] = {
		["buff_id"] = "12",
		["skill_icon"] = "soul_pic_soulicon012",
		["skill_name"] = "skill_name_12",
		["skill_tips"] = "skill_tips_12",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_purple",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_purplespot",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_purplespot",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["13"] = {
		["buff_id"] = "13",
		["skill_icon"] = "soul_pic_soulicon013",
		["skill_name"] = "skill_name_13",
		["skill_tips"] = "skill_tips_13",
		["launch_name"] = "0",
		["bullet_name"] = "NULL",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "NULL",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "NULL",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["14"] = {
		["buff_id"] = "14",
		["skill_icon"] = "soul_pic_soulicon014",
		["skill_name"] = "skill_name_14",
		["skill_tips"] = "skill_tips_14",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_purple",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_purplespot",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_laser",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["15"] = {
		["buff_id"] = "15",
		["skill_icon"] = "soul_pic_soulicon015",
		["skill_name"] = "skill_name_15",
		["skill_tips"] = "skill_tips_15",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_fire",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_red",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_fire",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["16"] = {
		["buff_id"] = "16",
		["skill_icon"] = "soul_pic_soulicon016",
		["skill_name"] = "skill_name_16",
		["skill_tips"] = "skill_tips_16",
		["launch_name"] = "0",
		["bullet_name"] = "NULL",
		["scatter_num"] = "1",
		["track_bullets_num"] = "0",
		["trajectory_name"] = "NULL",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "NULL",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "0",
		["angry"] = "0",

	},
	["17"] = {
		["buff_id"] = "17",
		["skill_icon"] = "soul_pic_soulicon017",
		["skill_name"] = "skill_name_17",
		["skill_tips"] = "skill_tips_17",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_fire",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_fire",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_fire",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["18"] = {
		["buff_id"] = "18",
		["skill_icon"] = "soul_pic_soulicon018",
		["skill_name"] = "skill_name_18",
		["skill_tips"] = "skill_tips_18",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_purple",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_red",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_bomb",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["19"] = {
		["buff_id"] = "19",
		["skill_icon"] = "soul_pic_soulicon019",
		["skill_name"] = "skill_name_19",
		["skill_tips"] = "skill_tips_19",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_purple",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_purplespot",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_purplespot",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["20"] = {
		["buff_id"] = "20",
		["skill_icon"] = "soul_pic_soulicon020",
		["skill_name"] = "skill_name_20",
		["skill_tips"] = "skill_tips_20",
		["launch_name"] = "0",
		["bullet_name"] = "fight_pic_blueice",
		["scatter_num"] = "1",
		["track_bullets_num"] = "1",
		["trajectory_name"] = "fight_pic_path_blueice",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "fight_mv_blizzard",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "-1000",
		["angry"] = "0",

	},
	["21"] = {
		["buff_id"] = "0",
		["skill_icon"] = "NULL",
		["skill_name"] = "单体加血",
		["skill_tips"] = "恢复自身800点生命.",
		["launch_name"] = "0",
		["bullet_name"] = "NULL",
		["scatter_num"] = "0",
		["track_bullets_num"] = "0",
		["trajectory_name"] = "NULL",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "NULL",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "0",
		["angry"] = "0",

	},
	["22"] = {
		["buff_id"] = "0",
		["skill_icon"] = "NULL",
		["skill_name"] = "群体加血",
		["skill_tips"] = "恢复友方所有成员600点生命.",
		["launch_name"] = "0",
		["bullet_name"] = "NULL",
		["scatter_num"] = "0",
		["track_bullets_num"] = "0",
		["trajectory_name"] = "NULL",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "NULL",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "0",
		["angry"] = "0",

	},
	["23"] = {
		["buff_id"] = "0",
		["skill_icon"] = "NULL",
		["skill_name"] = "单体隐身",
		["skill_tips"] = "自己获得隐身效果,持续3回合.",
		["launch_name"] = "0",
		["bullet_name"] = "NULL",
		["scatter_num"] = "0",
		["track_bullets_num"] = "0",
		["trajectory_name"] = "NULL",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "NULL",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "0",
		["angry"] = "0",

	},
	["24"] = {
		["buff_id"] = "0",
		["skill_icon"] = "NULL",
		["skill_name"] = "群体隐身",
		["skill_tips"] = "友方玩家获得隐身效果,持续2回合.",
		["launch_name"] = "0",
		["bullet_name"] = "NULL",
		["scatter_num"] = "0",
		["track_bullets_num"] = "0",
		["trajectory_name"] = "NULL",
		["trajectory_sound_name"] = "NULL",
		["explosion_name"] = "NULL",
		["explosion_sound_name"] = "NULL",
		["target_rule"] = "0",
		["target_hp"] = "0",
		["angry"] = "0",

	},

}
return define_skill
